rmdir /s /q Windows\.vs
rmdir /s /q Windows\aom.dir
rmdir /s /q Windows\aom_av1_common.dir
rmdir /s /q Windows\aom_av1_common_avx2_intrinsics.dir
rmdir /s /q Windows\aom_av1_common_sse2_intrinsics.dir
rmdir /s /q Windows\aom_av1_common_sse4_intrinsics.dir
rmdir /s /q Windows\aom_av1_common_ssse3_intrinsics.dir
rmdir /s /q Windows\aom_av1_decoder.dir
rmdir /s /q Windows\aom_av1_encoder.dir
rmdir /s /q Windows\aom_av1_encoder_avx2_intrinsics.dir
rmdir /s /q Windows\aom_av1_encoder_sse2_intrinsics.dir
rmdir /s /q Windows\aom_av1_encoder_sse2_static.dir
rmdir /s /q Windows\aom_av1_encoder_sse3_intrinsics.dir
rmdir /s /q Windows\aom_av1_encoder_sse4_intrinsics.dir
rmdir /s /q Windows\aom_av1_encoder_sse42_intrinsics.dir
rmdir /s /q Windows\aom_av1_encoder_ssse3_intrinsics.dir
rmdir /s /q Windows\aom_av1_encoder_ssse3_static.dir
rmdir /s /q Windows\aom_dsp.dir
rmdir /s /q Windows\aom_dsp_common.dir
rmdir /s /q Windows\aom_dsp_common_avx2_intrinsics.dir
rmdir /s /q Windows\aom_dsp_common_sse2_intrinsics.dir
rmdir /s /q Windows\aom_dsp_common_sse2_static.dir
rmdir /s /q Windows\aom_dsp_common_sse4_1_intrinsics.dir
rmdir /s /q Windows\aom_dsp_common_ssse3_intrinsics.dir
rmdir /s /q Windows\aom_dsp_common_ssse3_static.dir
rmdir /s /q Windows\aom_dsp_decoder.dir
rmdir /s /q Windows\aom_dsp_encoder.dir
rmdir /s /q Windows\aom_dsp_encoder_avx_intrinsics.dir
rmdir /s /q Windows\aom_dsp_encoder_avx2_intrinsics.dir
rmdir /s /q Windows\aom_dsp_encoder_sse2_intrinsics.dir
rmdir /s /q Windows\aom_dsp_encoder_sse2_static.dir
rmdir /s /q Windows\aom_dsp_encoder_sse4_1_intrinsics.dir
rmdir /s /q Windows\aom_dsp_encoder_ssse3_intrinsics.dir
rmdir /s /q Windows\aom_dsp_encoder_ssse3_static.dir
rmdir /s /q Windows\aom_mem.dir
rmdir /s /q Windows\aom_pc.dir
rmdir /s /q Windows\aom_ports_static.dir
rmdir /s /q Windows\aom_rtcd.dir
rmdir /s /q Windows\aom_scale.dir
rmdir /s /q Windows\aom_util.dir
rmdir /s /q Windows\aom_version.dir
rmdir /s /q Windows\asm_objects
rmdir /s /q Windows\av1_rc_qmode.dir
rmdir /s /q Windows\CMakeFiles
rmdir /s /q Windows\x64
rmdir /s /q Windows\yuv.dir
