rmdir /s /q Windows\.vs
rmdir /s /q Windows\CMakeFiles
rmdir /s /q Windows\lib\CMakeFiles
rmdir /s /q Windows\lib\jxl_dec-obj.dir
rmdir /s /q Windows\lib\jxl_enc-obj.dir
rmdir /s /q Windows\lib\jxl_threads-static.dir
rmdir /s /q Windows\lib\jxl-static.dir
rmdir /s /q Windows\third_party\brotli\brotlicommon-static.dir
rmdir /s /q Windows\third_party\brotli\brotlienc-static.dir
rmdir /s /q Windows\third_party\brotli\CMakeFiles
rmdir /s /q Windows\third_party\brotli\Release
