/******************************************************************************
MLT("", DE, "", FR, "", IT, "", SP, "", PO, "", PL, "", RU, "", JP, "", KO, "", CN, "", TH, "")
MLTC(u"", DE, u"", FR, u"", IT, u"", SP, u"", PO, u"", PL, u"", RU, u"", JP, u"", KO, u"", CN, u"", TH, u"")
cchar* T() {return MLTC(u"", DE, u"", FR, u"", IT, u"", SP, u"", PO, u"", PL, u"", RU, u"", JP, u"", KO, u"", CN, u"", TH, u"");}
/******************************************************************************/
#include "stdafx.h"
namespace EE{
/******************************************************************************/
CChar* TAction() {return MLTC(u"Action", DE, u"Aktion", FR, u"Action", IT, u"Azione", SP, u"Acción", PO, u"Açao", PL, u"Akcja", RU, u"Действие", JP, u"アクション", KO, u"동작", CN, u"行动", TH, u"หนังบู๊");}
CChar* TAmbientOcclusion() {return MLTC(u"Ambient Occlusion", DE, u"Umgebungsverdeckung (AO)", FR, u"Occlusion Ambiante (AO)", IT, u"Ambient Occlusion", SP, u"Oclusión Ambiental (AO)", PO, u"Oclusão de Ambiente (AO)", PL, u"Okluzja Otoczenia (AO)", RU, u"Окружающая Окклюзия"/*(AO)*/, JP, u"アンビエントオクルージョン (AO)", KO, u"앰비언트 어클루전 (AO)", CN, u"环境光遮蔽 (AO)", TH, u"การบดเคี้ยวรอบข้าง (AO)");}
CChar* TAmbientOcclusionRes() {return MLTC(u"Ambient Occlusion Buffers", DE, u"AO Auflösung", FR, u"Résolution AO", IT, u"Risoluzione AO", SP, u"Resolución de AO", PO, u"Resolução AO", PL, u"Rozdzielczość AO", RU, u"Разрешение АО", JP, u"AO 解像度", KO, u"AO 해상도", CN, u"AO 分辨率", TH, u"ความละเอียด AO");}
CChar* TAmbientVolume() {return MLTC(u"Ambient Volume", DE, u"Umgebungslautstärke", FR, u"Volume Ambiant", IT, u"Volume Ambientale", SP, u"Volumen Ambiente", PO, u"Volume Ambiente", PL, u"Głośność Otoczenia", RU, u"Объем Окружающей", JP, u"周囲の音量", KO, u"주변 볼륨", CN, u"环境音量", TH, u"ระดับเสียงแวดล้อม");}
CChar* TArachnids() {return MLTC(u"Arachnids", DE, u"Spinnentiere", FR, u"Arachnides", IT, u"Aracnidi", SP, u"Arácnidos", PO, u"Aracnídeos", PL, u"Arachnidy", RU, u"Паукообразные", JP, u"クモ類", KO, u"거미류", CN, u"蛛形纲动物", TH, u"แมง");}
CChar* TArmor() {return MLTC(u"Armor", DE, u"Rüstung", FR, u"Armure", IT, u"Armatura", SP, u"Armadura", PO, u"Armaduras", PL, u"Pancerz", RU, u"Броня", JP, u"鎧", KO, u"갑옷", CN, u"盔甲", TH, u"เกราะ");}
CChar* TArrow() {return MLTC(u"Arrow", DE, u"Pfeil", FR, u"Flèche", IT, u"Freccia", SP, u"Flecha", PO, u"Flecha", PL, u"Strzała", RU, u"Стрела", JP, u"矢印", KO, u"화살", CN, u"箭", TH, u"ลูกศร");}
CChar* TAuthor() {return MLTC(u"Author", DE, u"Autor", FR, u"Auteur", IT, u"Autore", SP, u"Autor", PO, u"Autor", PL, u"Autor", RU, u"Автор", JP, u"著者", KO, u"작가", CN, u"作者", TH, u"ผู้เขียน");}
CChar* TAxe() {return MLTC(u"Axe", DE, u"Axt", FR, u"Hache", IT, u"Ascia", SP, u"Hacha", PO, u"Machado", PL, u"Topór", RU, u"Топор", JP, u"斧", KO, u"도끼", CN, u"斧头", TH, u"ขวาน");}
CChar* TBack() {return MLTC(u"Back", DE, u"Zurück", FR, u"Arrière", IT, u"Ritorno", SP, u"Atrás", PO, u"Costas", PL, u"Wstecz", RU, u"Назад", JP, u"戻る", KO, u"뒤", CN, u"后退", TH, u"กลับ");}
CChar* TBlock() {return MLTC(u"Block", DE, u"Block", FR, u"Bloquer", IT, u"Bloccare", SP, u"Cuadra", PO, u"Bloquear", PL, u"Blok", RU, u"Блокировать", JP, u"ブロック", KO, u"차단하다", CN, u"堵塞", TH, u"ปิดกั้น");}
CChar* TBlocked(TRANS_FORM form) {return MLTC(u"Blocked", DE, u"Verstopft", FR, u"Bloqué", IT, u"Bloccato", SP, u"Obstruido", PO, u"Bloqueado", PL, (form==TF_MALE) ? u"Zablokowany" : (form==TF_FEMALE) ? u"Zablokowana" : u"Zablokowane", RU, u"Заблокирован", JP, u"塞がり", KO, u"막힌", CN, u"被封锁", TH, u"ถูกบล็อค");}
CChar* TBlue() {return MLTC(u"Blue", DE, u"Blau", FR, u"Bleu", IT, u"Blu", SP, u"Azul", PO, u"Azul", PL, u"Niebieski", RU, u"Синий", JP, u"青い", KO, u"푸른", CN, u"蓝色", TH, u"สีฟ้า");}
CChar* TBolt() {return MLTC(u"Bolt", DE, u"Bolzen", FR, u"Boulon", IT, u"Bullone", SP, u"Perno", PO, u"Parafuso", PL, u"Bełt", RU, u"Болт", JP, u"ボルト", KO, u"볼트", CN, u"弩螺栓", TH, u"กลอนหน้าไม้");}
CChar* TBow() {return MLTC(u"Bow", DE, u"Bogen", FR, u"Arc", IT, u"Arco", SP, u"Arco", PO, u"Arco", PL, u"Łuk", RU, u"Лук", JP, u"弓", KO, u"활", CN, u"弓", TH, u"คันธนู");}
CChar* TBrightness() {return MLTC(u"Brightness", DE, u"Helligkeit", FR, u"Luminosité", IT, u"Luminosità", SP, u"Brillo", PO, u"Brilho", PL, u"Jasność", RU, u"Яркость", JP, u"輝度", KO, u"명도", CN, u"亮度", TH, u"ความสว่าง");}
CChar* TBumpMapping() {return MLTC(u"Bump Mapping", DE, u"Bump Mapping", FR, u"Placage de Relief", IT, u"Mappatura degli Urti", SP, u"Mapeado Topológico", PO, u"Mapeamento de Colisão", PL, u"Mapowanie Wypukłości", RU, u"Рельефное Текстурирование", JP, u"バンプマッピング", KO, u"범프 매핑", CN, u"凹凸贴图", TH, u"การทำแผนที่ชน");}
CChar* TBuy() {return MLTC(u"Buy", DE, u"Kaufen", FR, u"Acheter", IT, u"Acquistare", SP, u"Comprar", PO, u"Comprar", PL, u"Kup", RU, u"Купить", JP, u"買う", KO, u"구입하다", CN, u"买", TH, u"ซื้อ");}
CChar* TCancel() {return MLTC(u"Cancel", DE, u"Stornieren", FR, u"Annuler", IT, u"Annulla", SP, u"Cancelar", PO, u"Cancelar", PL, u"Anuluj", RU, u"Отмена", JP, u"キャンセル", KO, u"취소", CN, u"取消", TH, u"ยกเลิก");}
CChar* TCantDropItemHere() {return MLTC(u"Can't drop item here", DE, u"Artikel kann hier nicht abgelegt werden", FR, u"Impossible de déposer l'article ici", IT, u"Impossibile rilasciare l'oggetto qui", SP, u"No se puede soltar el artículo aquí", PO, u"Não é possível soltar o item aqui", PL, u"Nie można upuścić tu przedmiotu", RU, u"Не могу бросить предмет сюда", JP, u"ここにアイテムをドロップできません", KO, u"여기에 아이템을 떨어뜨릴 수 없습니다", CN, u"不能在此处放置物品", TH, u"ดรอปไอเทมที่นี่ไม่ได้");}
CChar* TCantReadSpellBookNoMagic() {return
   MLTC(u"Can't read Spell Books with no Magic skill.",
    DE, u"Kann keine Zauberbücher ohne Magie Fertigkeit lesen.",
    FR, u"Impossible de lire les livres de sorts sans compétence magique.",
    IT, u"Non riesco a leggere libri di incantesimi senza abilità di magia.",
    SP, u"No puedo leer libros de hechizos sin habilidad mágica.",
    PO, u"Não pode ler Livros de Feitiços sem nenhuma habilidade de Magia.",
    PL, u"Nie można czytać Księgi Czarów bez umiejętności Magii.",
    RU, u"Не могу читать книги заклинаний без навыка магии.",
    JP, u"魔法のスキルがないと魔法の本を読むことはできません。",
    KO, u"마법 스킬이 없으면 스펠 북을 읽을 수 없습니다.",
    CN, u"没有魔法技能无法阅读法术书。",
    TH, u"ไม่สามารถอ่านหนังสือคาถาที่ไม่มีทักษะเวทย์มนตร์");}
CChar* TCartoon() {return MLTC(u"Cartoon", DE, u"Karikatur", FR, u"Caricature", IT, u"Cartone", SP, u"Caricatura", PO, u"Caricatura", PL, u"Kreskówka", RU, u"Мультфильм", JP, u"アニメーション", KO, u"만화", CN, u"卡通片", TH, u"การ์ตูน");}
CChar* TCastle() {return MLTC(u"Castle", DE, u"Schloss", FR, u"Château", IT, u"Castello", SP, u"Castillo", PO, u"Castelo", PL, u"Zamek", RU, u"Замок", JP, u"城", KO, u"성", CN, u"城堡", TH, u"ปราสาท");}
CChar* TCastSpell() {return MLTC(u"Cast Spell", DE, u"Zauber Wirken", FR, u"Lancer un Sort", IT, u"Lancia Incantesimi", SP, u"Lanzar Hechizo", PO, u"Conjurar Feitiço", PL, u"Rzuć Czar", RU, u"Произнести Заклинание", JP, u"キャストスペル", KO, u"주문 시전", CN, u"施法", TH, u"ร่ายคาถา");}
CChar* TCave() {return MLTC(u"Cave", DE, u"Höhle", FR, u"Grotte", IT, u"Grotta", SP, u"Cueva", PO, u"Caverna", PL, u"Jaskinia", RU, u"Пещера", JP, u"洞窟", KO, u"동굴", CN, u"洞穴", TH, u"ถ้ำ");}
CChar* TCellar() {return MLTC(u"Cellar", DE, u"Keller", FR, u"Cave", IT, u"Cantina", SP, u"Cava", PO, u"Porão", PL, u"Piwnica", RU, u"Подвал", JP, u"セラー", KO, u"지하실", CN, u"地窖", TH, u"ห้องใต้ดิน");}
CChar* TChangeItem() {return MLTC(u"Change Item", DE, u"Artikel Ändern", FR, u"Changer d'Article", IT, u"Cambia Articolo", SP, u"Elemento de Cambio", PO, u"Alterar Item", PL, u"Zmień Przedmiot", RU, u"Изменить Элемент", JP, u"アイテムの変更", KO, u"아이템 변경", CN, u"更改项目", TH, u"เปลี่ยนรายการ");}
CChar* TCharacterScreen() {return MLTC(u"Character Screen", DE, u"Zeichenbildschirm", FR, u"Écran de Personnage", IT, u"Schermata dei Personaggi", SP, u"Pantalla de Personaje", PO, u"Tela de Personagem", PL, u"Ekran Postaci", RU, u"Экран Персонажа", JP, u"キャラクター画面", KO, u"캐릭터 화면", CN, u"人物画面", TH, u"หน้าจอตัวละคร");}
CChar* TChest() {return MLTC(u"Chest", DE, u"Truhe", FR, u"Coffre", IT, u"Cassa", SP, u"Cofre", PO, u"Cofre", PL, u"Skrzynia", RU, u"Сундук", JP, u"金庫", KO, u"상자", CN, u"箱", TH, u"หีบ");}
CChar* TChestKey() {return MLTC(u"Chest Key", DE, u"Truhenschlüssel", FR, u"Clé du Coffre", IT, u"Chiave del Torace", SP, u"Llave de Cofre", PO, u"Chave do Baú", PL, u"Klucz do Skrzyni", RU, u"Ключ от Сундука", JP, u"チェストキー", KO, u"가슴 열쇠", CN, u"宝箱钥匙", TH, u"กุญแจหน้าอก");}
CChar* TClass() {return MLTC(u"Class", DE, u"Klasse", FR, u"Classer", IT, u"Classe", SP, u"Clase", PO, u"Classe", PL, u"Klasa", RU, u"Сорт", JP, u"クラス", KO, u"수업", CN, u"班级", TH, u"ระดับ");}
CChar* TClick() {return MLTC(u"Click", DE, u"Klicken", FR, u"Cliquet", IT, u"Clic", SP, u"Clic", PO, u"Clique", PL, u"Klik", RU, u"Нажмите", JP, u"クリック", KO, u"클릭", CN, u"点击", TH, u"คลิก");}
CChar* TClose() {return MLTC(u"Close", DE, u"Schließen", FR, u"Fermer", IT, u"Chiudere", SP, u"Cerrar", PO, u"Fechar", PL, u"Zamknij", RU, u"Закрыть", JP, u"シャット", KO, u"닫다", CN, u"关闭", TH, u"ปิด");}
CChar* TCloseActiveWindow() {return MLTC(u"Close Active Window", DE, u"Aktives Fenster schließen", FR, u"Fermer la fenêtre active", IT, u"Chiudi la finestra attiva", SP, u"Cerrar ventana activa", PO, u"Fechar janela ativa", PL, u"Zamknij aktywne okno", RU, u"Закрыть активное окно", JP, u"アクティブウィンドウを閉じる", KO, u"활성 창 닫기", CN, u"关闭活动窗口", TH, u"ปิดหน้าต่างที่ใช้งานอยู่");}
CChar* TClub() {return MLTC(u"Club", DE, u"Knüppel", FR, u"Trique", IT, u"Cazzuola", SP, u"Porra", PO, u"Porrete", PL, u"Maczuga", RU, u"Дубина", JP, u"棍棒", KO, u"곤장", CN, u"棍棒", TH, u"ตะบอง");}
CChar* TCollected() {return MLTC(u"Collected", DE, u"Gesammelt", FR, u"Collecté", IT, u"Raccolto", SP, u"Recogido", PO, u"Coletado", PL, u"Pobrano", RU, u"Собрано", JP, u"集めました", KO, u"모은", CN, u"集", TH, u"สะสม");}
CChar* TConfigureControllers() {return MLTC(u"Configure Controllers", DE, u"Controller Konfigurieren", FR, u"Configurer les Contrôleurs", IT, u"Configura Controller", SP, u"Configurar Controladores", PO, u"Configurar Controladores", PL, u"Konfiguruj Kontrolery", RU, u"Настройка Контроллеров", JP, u"コントローラーの構成", KO, u"컨트롤러 구성", CN, u"配置控制器", TH, u"กำหนดค่าคอนโทรลเลอร์");}
Str    TCreatedBy(CChar *name) {return MLT(S+"Created by "+name, DE, S+u"Erstellt von "+name, FR, S+u"Créé par "+name, IT, S+u"Creato da "+name, SP, S+u"Creado por "+name, PO, S+u"Criado por "+name, PL, S+u"Stworzone przez "+name, RU, S+u"Создано "+name, JP, S+name+u" によって作成されました", KO, S+u"만든 사람 "+name, CN, S+u"由 "+name+u" 创建", TH, S+u"สร้างโดย "+name);}
CChar* TCrossbow() {return MLTC(u"Crossbow", DE, u"Armbrust", FR, u"Arbalète", IT, u"Balestra", SP, u"Ballesta", PO, u"Besta", PL, u"Kusza", RU, u"Самострел", JP, u"クロスボウ", KO, u"석궁", CN, u"弩", TH, u"หน้าไม้");}
CChar* TCrypt() {return MLTC(u"Crypt", DE, u"Krypta", FR, u"Crypte", IT, u"Cripta", SP, u"Cripta", PO, u"Cripta", PL, u"Krypta", RU, u"Склеп", JP, u"クリプト", KO, u"토굴", CN, u"地穴", TH, u"ฝังศพใต้ถุนโบสถ์");}
CChar* TCustom(TRANS_FORM form) {return MLTC(u"Custom", DE, u"Brauch", FR, u"Personnalisé", IT, u"Costume", SP, u"Personalizado", PO, u"Personalizado", PL, (form==TF_MALE) ? u"Własny" : (form==TF_FEMALE) ? u"Własna" : u"Własne", RU, u"Редактор", JP, u"編集者", KO, u"편집자", CN, u"编辑", TH, u"บรรณาธิการ");}
CChar* TDash() {return MLTC(u"Dash", DE, u"Sprint", FR, u"Sprint", IT, u"Sprint", SP, u"Pique", PO, u"Corrida", PL, u"Sprint", RU, u"Спринт", JP, u"ダッシュ", KO, u"대시", CN, u"短跑", TH, u"วิ่ง");}
CChar* TDagger() {return MLTC(u"Dagger", DE, u"Dolch", FR, u"Dague", IT, u"Pugnale", SP, u"Daga", PO, u"Punhal", PL, u"Sztylet", RU, u"Кинжал", JP, u"短剣", KO, u"단검", CN, u"匕首", TH, u"กริช");}
CChar* TDamage() {return MLTC(u"Damage", DE, u"Attacke", FR, u"Dommage", IT, u"Danno", SP, u"Daño", PO, u"Dano", PL, u"Atak", RU, u"Атака", JP, u"ダメージ", KO, u"공격", CN, u"攻击", TH, u"จู่โจม");}
CChar* TDamageL() {return MLTC(u"DamageL", DE, u"AttackeL", FR, u"DommageL", IT, u"DannoL", SP, u"DañoI", PO, u"DanoE", PL, u"AtakL", RU, u"АтакаО", JP, u"左攻撃", KO, u"왼쪽 공격", CN, u"左攻击", TH, u"โจมตีซ้าย");}
CChar* TDamageR() {return MLTC(u"DamageR", DE, u"AttackeR", FR, u"DommageD", IT, u"DannoD", SP, u"DañoD", PO, u"DanoC", PL, u"AtakP", RU, u"АтакаВ", JP, u"攻撃権", KO, u"오른쪽 공격", CN, u"攻击权", TH, u"โจมตีขวา");}
CChar* TDelete() {return MLTC(u"Delete", DE, u"Löschen", FR, u"Supprimer", IT, u"Eliminare", SP, u"Borrar", PO, u"Excluir", PL, u"Usuń", RU, u"Удалить", JP, u"消去", KO, u"삭제", CN, u"删除", TH, u"ลบ");}
CChar* TDeviceVibration() {return MLTC(u"Device Vibration", DE, u"Gerätevibration", FR, u"Vibration de l'Appareil", IT, u"Vibrazione del Dispositivo", SP, u"Vibración del Dispositivo", PO, u"Vibração do Dispositivo", PL, u"Wibracje Urządzenia", RU, u"Вибрация Устройства", JP, u"デバイスの振動", KO, u"장치 진동", CN, u"设备振动", TH, u"การสั่นสะเทือนของอุปกรณ์");}
CChar* TDexterity() {return MLTC(u"Dexterity", DE, u"Geschickl."/*Geschicklichkeit*/, FR, u"Dextérité", IT, u"Destrezza", SP, u"Destreza", PO, u"Destreza", PL, u"Zręczność", RU, u"Ловкость", JP, u"器用さ", KO, u"재치", CN, u"灵巧", TH, u"ความคล่องแคล่ว");}
CChar* TDifficulty() {return MLTC(u"Difficulty", DE, u"Schwierigkeit", FR, u"Difficulté", IT, u"Difficoltà", SP, u"Dificultad", PO, u"Dificuldade", PL, u"Trudność", RU, u"Сложность", JP, u"困難", KO, u"어려움", CN, u"困难", TH, u"ความยาก");}
CChar* TDoor() {return MLTC(u"Door", DE, u"Tür", FR, u"Porte", IT, u"Porta", SP, u"Puerta", PO, u"Porta", PL, u"Drzwi", RU, u"Дверь", JP, u"ドア", KO, u"문", CN, u"门", TH, u"ประตู");}
CChar* TDoorKey() {return MLTC(u"Door Key", DE, u"Türschlüssel", FR, u"Clé de la Porte", IT, u"Chiave della Porta", SP, u"Llave de la Puerta", PO, u"Chave da Porta", PL, u"Klucz do Drzwi", RU, u"Дверной Ключ", JP, u"ドアキー", KO, u"문 열쇠", CN, u"门钥匙", TH, u"กุญแจประตู");}
CChar* TDownload() {return MLTC(u"Download", DE, u"Herunterladen", FR, u"Télécharger", IT, u"Scaricamento", SP, u"Descargar", PO, u"Download", PL, u"Pobierz", RU, u"Скачать", JP, u"ダウンロード", KO, u"다운로드", CN, u"下载", TH, u"ดาวน์โหลด");}
CChar* TDownloaded() {return MLTC(u"Downloaded", DE, u"Heruntergeladen", FR, u"Téléchargé", IT, u"Scaricato", SP, u"Descargado", PO, u"Baixado", PL, u"Pobrano", RU, u"Скачано", JP, u"ダウンロード", KO, u"다운로드됨", CN, u"已下载", TH, u"ดาวน์โหลดแล้ว");}
CChar* TDownloads() {return MLTC(u"Downloads", DE, u"Downloads", FR, u"Téléchargements", IT, u"Download", SP, u"Descargas", PO, u"Transferências", PL, u"Pobrań", RU, u"Загрузки", JP, u"ダウンロード", KO, u"다운로드", CN, u"下载", TH, u"ดาวน์โหลด");}
CChar* TDrawn() {return MLTC(u"Drawn", DE, u"Gezeichnet", FR, u"Dessiné", IT, u"Disegnato", SP, u"Dibujado", PO, u"Retirou", PL, u"Rysowany", RU, u"Нарисовано", JP, u"描かれた", KO, u"그어진", CN, u"画", TH, u"วาด");}
CChar* TDrink() {return MLTC(u"Drink", DE, u"Trinken", FR, u"Buvez", IT, u"Bevi", SP, u"Bebe", PO, u"Beba", PL, u"Wypij", RU, u"Выпей", JP, u"飲む", KO, u"마시다", CN, u"喝", TH, u"ดื่ม");}
CChar* TDrop() {return MLTC(u"Drop", DE, u"Tropfen", FR, u"Laissez tomber", IT, u"Far cadere", SP, u"Soltar", PO, u"Derrubar", PL, u"Upuść", RU, u"Уронить", JP, u"落とす", KO, u"하락", CN, u"降低", TH, u"หยด");}
CChar* TDungeon() {return MLTC(u"Dungeon", DE, u"Verlies", FR, u"Donjon", IT, u"Dungeon", SP, u"Calabozo", PO, u"Masmorra", PL, u"Loch", RU, u"Подземелье", JP, u"ダンジョン", KO, u"지하 감옥", CN, u"地牢", TH, u"ดันเจี้ยน");}
CChar* TDwarvenMine() {return MLTC(u"Dwarven Mine", DE, u"Zwergenmine", FR, u"Mine Naine", IT, u"Miniera Nanica", SP, u"Mina Enana", PO, u"Mina dos Anões", PL, u"Kopalnia Krasnoludów", RU, u"Гномья Шахта", JP, u"ドワーフ鉱山", KO, u"드워프 광산", CN, u"矮人矿", TH, u"เหมืองคนแคระ");}
CChar* TEasy(TRANS_FORM form) {return MLTC(u"Easy", DE, u"Leicht", FR, u"Facile", IT, u"Facile", SP, u"Fácil", PO, u"Fácil", PL, (form==TF_MALE) ? u"Łatwy" : (form==TF_FEMALE) ? u"Łatwa" : u"Łatwe", RU, u"Легкий", JP, u"簡単", KO, u"쉬운", CN, u"简单", TH, u"ง่าย");}
CChar* TEdgeSoftening() {return MLTC(u"Edge Softening", DE, u"Kantenweichzeichnung", FR, u"Adoucissement des Bords", IT, u"Ammorbidimento dei Bordi", SP, u"Suavizado de Bordes", PO, u"Suavização de Bordas", PL, u"Zmiękczanie Krawędzi", RU, u"Смягчение Краев", JP, u"エッジ軟化", KO, u"가장자리 부드럽게 하기", CN, u"边缘软化", TH, u"ขอบนุ่ม");}
CChar* TEdit() {return MLTC(u"Edit", DE, u"Bearbeiten", FR, u"Modifier", IT, u"Modificare", SP, u"Editar", PO, u"Editar", PL, u"Edytuj", RU, u"Редактировать", JP, u"編集", KO, u"편집하다", CN, u"编辑", TH, u"แก้ไข");}
CChar* TEditor() {return MLTC(u"Editor", DE, u"Editor", FR, u"Éditeur", IT, u"Editore", SP, u"Editor", PO, u"Editor", PL, u"Edytor", RU, u"Редактор", JP, u"編集者", KO, u"편집자", CN, u"编辑", TH, u"บรรณาธิการ");}
CChar* TEgyptianTomb() {return MLTC(u"Egyptian Tomb", DE, u"Ägyptisches Grab", FR, u"Tombeau Égyptien", IT, u"Tomba Egizia", SP, u"Tumba Egipcia", PO, u"Tumba Egípcia", PL, u"Grób Egipski", RU, u"Египетская Гробница", JP, u"エジプトの墓", KO, u"이집트 무덤", CN, u"埃及墓", TH, u"สุสานอียิปต์");}
CChar* TEquip() {return MLTC(u"Equip", DE, u"Ausrüsten", FR, u"Équiper", IT, u"Equipaggia", SP, u"Equipar", PO, u"Equipar", PL, u"Wyposaż", RU, u"Оборудовать", JP, u"装備", KO, u"갖추어 주다", CN, u"装备", TH, u"อุปกรณ์");}
CChar* TExclusive() {return MLTC(u"Exclusive", DE, u"Exklusiv", FR, u"Exclusif", IT, u"Esclusivo", SP, u"Exclusivo", PO, u"Exclusivo", PL, u"Ekskluzywny", RU, u"Эксклюзивный", JP, u"エクスクルーシブ", KO, u"독점적 인", CN, u"独家的", TH, u"พิเศษ");}
CChar* TExitToSystem() {return MLTC(u"Exit to System", DE, u"Knappes Spiel", FR, u"Fermer le jeu", IT, u"Gioco chiuso", SP, u"Cerrar juego", PO, u"Fechar jogo", PL, u"Zamknij Grę", RU, u"Закрыть игру", JP, u"ゲームを閉じる", KO, u"게임 닫기", CN, u"关闭游戏", TH, u"ปิดเกม");}
CChar* TExp() {return MLTC(u"Exp.", DE, u"Erfahrung", FR, u"Exp.", IT, u"Esp.", SP, u"Exp.", PO, u"Exp.", PL, u"Dośw.", RU, u"Опыт", JP, u"経験", KO, u"경험", CN, u"经验", TH, u"ชำนาญ");}
CChar* TExperience() {return MLTC(u"Experience", DE, u"Erfahrung", FR, u"Expérience", IT, u"Esperienza", SP, u"Experiencia", PO, u"Experiência", PL, u"Doświadczenie", RU, u"Опыт", JP, u"経験", KO, u"경험", CN, u"经验", TH, u"ประสบการณ์");}
CChar* TEyeAdaptation() {return MLTC(u"Eye Adaptation", DE, u"Augenanpassung", FR, u"Adaptation des Yeux", IT, u"Adattamento Oculare", SP, u"Adaptación Ocular", PO, u"Adaptação dos Olhos", PL, u"Adaptacja Oka", RU, u"Адаптация Глаз", JP, u"目の適応", KO, u"눈 적응", CN, u"眼睛适应", TH, u"การปรับสายตา");}
CChar* TFeedback() {return MLTC(u"Feedback", DE, u"Feedback", FR, u"Réaction", IT, u"Risposta", SP, u"Opinión", PO, u"Comentários", PL, u"Opinia", RU, u"Мнение", JP, u"フィードバック", KO, u"피드백", CN, u"回馈", TH, u"ข้อเสนอแนะ");}
CChar* TFeedbackOK() {return MLTC(u"Feedback received, thank you.", DE, u"Feedback erhalten, danke.", FR, u"Commentaires reçus, merci.", IT, u"Feedback ricevuto, grazie.", SP, u"Comentarios recibidos, gracias.", PO, u"Feedback recebido, obrigado.", PL, u"Opinia otrzymana, dziękujemy.", RU, u"Отзыв получен, спасибо.", JP, u"フィードバックをいただき、ありがとうございます。", KO, u"피드백을 받았습니다. 감사합니다.", CN, u"收到反馈，谢谢。", TH, u"ได้รับคำติชมแล้ว ขอบคุณครับ");}
CChar* TFeedbackError() {return MLTC(u"There was an error sending feedback, please try again later.", DE, u"Beim Senden des Feedbacks ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.", FR, u"Une erreur s'est produite lors de l'envoi des commentaires, veuillez réessayer plus tard.", IT, u"Si è verificato un errore durante l'invio del feedback, riprova più tardi.", SP, u"Hubo un error al enviar los comentarios, inténtalo de nuevo más tarde.", PO, u"Ocorreu um erro ao enviar o feedback, tente novamente mais tarde.", PL, u"Wystąpił błąd podczas wysyłania opinii, spróbuj ponownie później.", RU, u"При отправке отзыва произошла ошибка, повторите попытку позже.", JP, u"フィードバックの送信中にエラーが発生しました。しばらくしてからもう一度お試しください。", KO, u"피드백을 보내는 동안 오류가 발생했습니다. 나중에 다시 시도해 주세요.", CN, u"发送反馈时出错，请稍后重试。", TH, u"เกิดข้อผิดพลาดในการส่งความคิดเห็น โปรดลองอีกครั้งในภายหลัง");}
CChar* TFieldOfView() {return MLTC(u"Field of View", DE, u"Sichtfeld (FOV)", FR, u"Champ de Vision (FOV)", IT, u"Campo Visivo (FOV)", SP, u"Campo de Visión (FOV)", PO, u"Campo de Visão (FOV)", PL, u"Pole Widzenia (FOV)", RU, u"Поле Зрения (FOV)", JP, u"視野 (FOV)", KO, u"시야 (FOV)", CN, u"视野 (FOV)", TH, u"ขอบเขตการมองเห็น (FOV)");}
CChar* TFireball() {return MLTC(u"Fireball", DE, u"Feuerball", FR, u"Boule de Feu", IT, u"Bolide", SP, u"Bola de Fuego", PO, u"Bola Fogo", PL, u"Kula Ognia", RU, u"Огненный Шар", JP, u"火球", KO, u"화구", CN, u"火球", TH, u"ลูกไฟ");}
CChar* TFireBomb() {return MLTC(u"Fire Bomb", DE, u"Brandbombe", FR, u"Bombe de Feu", IT, u"Bomba Incendiaria", SP, u"Bomba de Fuego", PO, u"Bomba de Incêndio", PL, u"Ognista Bomba", RU, u"Огненная Бомба", JP, u"火爆弾", KO, u"화염 폭탄", CN, u"火焰炸弹", TH, u"ระเบิดไฟ");}
CChar* TFloorPlate() {return MLTC(u"Floor Plate", DE, u"Bodenplatte", FR, u"Plaque de Sol", IT, u"Piatto da Pavimento", SP, u"Placa de Piso", PO, u"Placa de Piso", PL, u"Płyta Podłogowa", RU, u"Напольная Плита", JP, u"フロアプレート", KO, u"바닥 판", CN, u"楼板", TH, u"แผ่นพื้น");}
CChar* TFor() {return MLTC(u"for", DE, u"für", FR, u"pour", IT, u"per", SP, u"por", PO, u"para", PL, u"za", RU, u"за", JP, u"", KO, u"", CN, u"", TH, u"เพื่อ");} // buy/sell for
CChar* TForgottenTemple() {return MLTC(u"Forgotten Temple", DE, u"Vergessener Tempel", FR, u"Temple Oublié", IT, u"Tempio Dimenticato", SP, u"Templo Olvidado", PO, u"Templo Esquecido", PL, u"Zapomniana Świątynia", RU, u"Забытый Храм", JP, u"忘れられた寺院", KO, u"잊혀진 사원", CN, u"被遗忘的寺庙", TH, u"วัดที่ถูกลืม");}
CChar* TFreeze() {return MLTC(u"Freeze", DE, u"Einfrieren", FR, u"Geler", IT, u"Congelare", SP, u"Congelar", PO, u"Congelar", PL, u"Zamrożenie", RU, u"Заморозить", JP, u"氷結", KO, u"얼다", CN, u"冻结", TH, u"แช่แข็ง");}
CChar* TFreezeBomb() {return MLTC(u"Freeze Bomb", DE, u"Gefrierbombe", FR, u"Bombe Glaciale", IT, u"Bomba Gelata", SP, u"Bomba Congelante", PO, u"Bomba Congelante", PL, u"Zamrażająca Bomba", RU, u"Морозильная Бомба", JP, u"フリーズボム", KO, u"동결 폭탄", CN, u"冷冻炸弹", TH, u"ระเบิดเยือกแข็ง");}
CChar* TFullHealthReached() {return MLTC(u"Full Health reached", DE, u"Volle Gesundheit erreicht", FR, u"Santé complète atteinte", IT, u"Piena salute raggiunta", SP, u"Salud completa alcanzada", PO, u"Saúde total alcançada", PL, u"Osiągnięto pełne zdrowie", RU, u"Полное здоровье достигнуто", JP, u"フルヘルスに達しました", KO, u"전체 건강 도달", CN, u"完全健康达到", TH, u"สุขภาพแข็งแรงสมบูรณ์");}
CChar* TFullscreen() {return MLTC(u"Fullscreen", DE, u"Vollbild", FR, u"Plein Écran", IT, u"A Schermo Intero", SP, u"Pantalla Completa", PO, u"Tela Cheia", PL, u"Pełny Ekran", RU, u"Полноэкранный", JP, u"全画面表示", KO, u"전체 화면", CN, u"全屏", TH, u"เต็มจอ");}
CChar* TGamePadDeadZone() {return MLTC(u"GamePad DeadZone", DE, u"GamePad Totzone", FR, u"Zone Morte de la Manette", IT, u"Zona Morta del GamePad", SP, u"GamePad Zona Muerta", PO, u"Zona Morta do GamePad", PL, u"Martwa Strefa GamePada", RU, u"Геймпад Мертвая Зона", JP, u"ゲームパッドデッドゾーン", KO, u"게임패드 데드존", CN, u"游戏手柄死区", TH, u"เกมแพดเดดโซน");}
CChar* TGamePadSensitivity() {return MLTC(u"GamePad Sensitivity", DE, u"GamePad Empfindlichkeit", FR, u"Sensibilité de la Manette", IT, u"Sensibilità del GamePad", SP, u"Sensibilidad del GamePad", PO, u"Sensibilidade do GamePad", PL, u"Czułość GamePada", RU, u"Чувствительность Геймпада", JP, u"ゲームパッドの感度", KO, u"게임패드 감도", CN, u"游戏手柄灵敏度", TH, u"ความไวของจอยแพด");}
CChar* TGamePadVibration() {return MLTC(u"GamePad Vibration", DE, u"GamePad Vibration", FR, u"Vibration de la Manette", IT, u"Vibrazione del GamePad", SP, u"Vibración del GamePad", PO, u"Vibração do GamePad", PL, u"Wibracje GamePada", RU, u"Вибрация Геймпада", JP, u"ゲームパッドの振動", KO, u"게임패드 진동", CN, u"游戏手柄振动", TH, u"การสั่นสะเทือนของเกมแพด");}
CChar* TGold() {return MLTC(u"Gold", DE, u"Gold", FR, u"Or", IT, u"Oro", SP, u"Oro", PO, u"Ouro", PL, u"Złoto", RU, u"Золото", JP, u"ゴールド", KO, u"금", CN, u"金子", TH, u"ทอง");}
CChar* TGround() {return MLTC(u"Ground", DE, u"Boden", FR, u"Sol", IT, u"Terra", SP, u"Terrestre", PO, u"Terra", PL, u"Grunt", RU, u"Земля", JP, u"接地", KO, u"지면", CN, u"地面", TH, u"พื้น");}
CChar* TGuiScale() {return MLTC(u"Gui Scale", DE, u"Schnittstellenskala", FR, u"Échelle d'Interface", IT, u"Scala di Interfaccia", SP, u"Escala de Interfaz", PO, u"Escala de Interface", PL, u"Skala Interfejsu", RU, u"Масштаб Интерфейса", JP, u"インターフェーススケール", KO, u"인터페이스 스케일", CN, u"界面规模", TH, u"มาตราส่วนอินเทอร์เฟซ");}
CChar* THammer() {return MLTC(u"Hammer", DE, u"Hammer", FR, u"Marteau", IT, u"Martello", SP, u"Martillo", PO, u"Martelo", PL, u"Młot", RU, u"Молоток", JP, u"ハンマー", KO, u"망치", CN, u"锤子", TH, u"ค้อน");}
CChar* THat() {return MLTC(u"Hat", DE, u"Hut", FR, u"Chapeau", IT, u"Cappello", SP, u"Sombrero", PO, u"Chapéu", PL, u"Kapelusz", RU, u"Шляпа", JP, u"帽子", KO, u"모자", CN, u"帽子", TH, u"หมวก");}
CChar* THeal() {return MLTC(u"Heal", DE, u"Heilen", FR, u"Guérir", IT, u"Guarire", SP, u"Curar", PO, u"Curar", PL, u"Uzdrowienie", RU, u"Лечить", JP, u"癒し", KO, u"치유하다", CN, u"愈合", TH, u"รักษา");}
CChar* THealth() {return MLTC(u"Health", DE, u"Gesundheit", FR, u"Santé", IT, u"Salute", SP, u"Salud", PO, u"Saúde", PL, u"Zdrowie", RU, u"Здоровье", JP, u"健康", KO, u"건강", CN, u"健康", TH, u"สุขภาพ");}
CChar* THealthPotion() {return MLTC(u"Health Potion", DE, u"Gesundheitstrank", FR, u"Potion de Vie", IT, u"Pozione di Salute", SP, u"Poción de Salud", PO, u"Poção de Saúde", PL, u"Eliksir Zdrowia", RU, u"Зелье Здоровья", JP, u"健康ポーション", KO, u"건강의 묘약", CN, u"健康药水", TH, u"ยาเพื่อสุขภาพ");}
CChar* THelmet() {return MLTC(u"Helmet", DE, u"Helm", FR, u"Casque", IT, u"Casco", SP, u"Casco", PO, u"Capacete", PL, u"Hełm", RU, u"Шлем", JP, u"ヘルメット", KO, u"헬멧", CN, u"头盔", TH, u"หมวกนิรภัย");}
CChar* THeroes() {return MLTC(u"Heroes", DE, u"Helden", FR, u"Héros", IT, u"Eroi", SP, u"Héroes", PO, u"Heróis", PL, u"Bohaterowie", RU, u"Герои", JP, u"ヒーローズ", KO, u"영웅", CN, u"英雄", TH, u"ฮีโร่");}
CChar* THeroLevel() {return MLTC(u"Hero Level", DE, u"Heldenlevel", FR, u"Niveau de Héros", IT, u"Livello Eroe", SP, u"Nivel de Héroe", PO, u"Nível de Herói", PL, u"Poziom Bohatera", RU, u"Уровень Героя", JP, u"ヒーローレベル", KO, u"영웅 레벨", CN, u"英雄等级", TH, u"ระดับฮีโร่");}
CChar* THigh(TRANS_FORM form) {return MLTC(u"High", DE, u"Hoch", FR, u"Haut", IT, u"Alto", SP, u"Alto", PO, u"Alto", PL, (form==TF_MALE) ? u"Wysoki" : (form==TF_FEMALE) ? u"Wysoka" : u"Wysokie", RU, u"Высоко", JP, u"高い", KO, u"높은", CN, u"高的", TH, u"สูง");}
CChar* THighPrecLight() {return MLTC(u"High Precision Light RT", DE, u"Präzises Licht", FR, u"Lumière Précise", IT, u"Luce Precisa", SP, u"Luz Precisa", PO, u"Luz Precisa", PL, u"Precyzyjne Oświetlenie", RU, u"Точный Свет", JP, u"高精度ライト", KO, u"고정밀 조명", CN, u"高精度灯", TH, u"แสงความแม่นยำสูง");}
CChar* THighPrecLitCol() {return MLTC(u"High Precision LitColor RT", DE, u"Präzise Farbe", FR, u"Couleur Précise", IT, u"Colore Preciso", SP, u"Color Preciso", PO, u"Cor Precisa", PL, u"Precyzyjny Kolor", RU, u"Точный Цвет", JP, u"高精度カラー", KO, u"고정밀 색상", CN, u"高精度颜色", TH, u"สีที่มีความแม่นยำสูง");}
CChar* TImprove() {return MLTC(u"Improve", DE, u"Verbessern", FR, u"Améliorer", IT, u"Ottimizzare", SP, u"Mejorar", PO, u"Melhorar", PL, u"Ulepsz", RU, u"Улучшать", JP, u"向上", KO, u"개선하다", CN, u"提升", TH, u"ปรับปรุง");}
CChar* TIncreasedSpellLevel() {return MLTC(u"Increased Spell Level", DE, u"Erhöhte Zauberstufe", FR, u"Augmentation du Niveau de Sort", IT, u"Livello dell'Incantesimo Aumentato", SP, u"Nivel de Hechizo Aumentado", PO, u"Nível de Feitiço Aumentado", PL, u"Ulepszono Poziom Czaru", RU, u"Повышенный Уровень Заклинаний", JP, u"スペルレベルの増加", KO, u"주문 레벨 증가", CN, u"增加法术等级", TH, u"เพิ่มระดับคาถา");}
CChar* TInvalidEmail() {return MLTC(u"Invalid Email", DE, u"Ungültige Email", FR, u"Email Invalide", IT, u"E-mail Non Valido", SP, u"Email Inválido", PO, u"Email Inválido", PL, u"Błędny Email", RU, u"Неверный адрес электронной почты", JP, u"無効なメール", KO, u"잘못된 이메일", CN, u"不合规电邮", TH, u"อีเมลไม่ถูกต้อง");}
CChar* TInventory() {return MLTC(u"Inventory", DE, u"Inventar", FR, u"Inventaire", IT, u"Inventario", SP, u"Inventario", PO, u"Inventário", PL, u"Inwentarz", RU, u"Инвентарь", JP, u"在庫", KO, u"목록", CN, u"存货", TH, u"รายการสิ่งของ");}
CChar* TKeep() {return MLTC(u"Keep", DE, u"Festung", FR, u"Forteresse", IT, u"Fortezza", SP, u"Fortaleza", PO, u"Fortaleza", PL, u"Twierdza", RU, u"Крепость", JP, u"要塞", KO, u"요새", CN, u"堡垒", TH, u"ป้อม");}
CChar* TKilledMonsters() {return MLTC(u"Killed Monsters", DE, u"Getötete Monster", FR, u"Monstres Tués", IT, u"Mostri Uccisi", SP, u"Monstruos Asesinados", PO, u"Monstros Abatidos", PL, u"Zabite Potwory", RU, u"Убитые Монстры", JP, u"殺されたモンスター", KO, u"살해된 몬스터", CN, u"杀死的怪物", TH, u"มอนสเตอร์ที่ถูกสังหาร");}
CChar* TKnife() {return MLTC(u"Knife", DE, u"Messer", FR, u"Couteau", IT, u"Coltello", SP, u"Cuchillo", PO, u"Faca", PL, u"Nóż", RU, u"Нож", JP, u"ナイフ", KO, u"칼", CN, u"刀", TH, u"มีด");}
CChar* TKnockout() {return MLTC(u"Knockout", DE, u"Schlagen", FR, u"Assommer", IT, u"Tramortire", SP, u"Knockear", PO, u"Nocaute", PL, u"Nokaut", RU, u"Нокаут", JP, u"ノックアウト", KO, u"녹아웃", CN, u"昏死", TH, u"น็อกคู่ต่อสู้");}
CChar* TLanguage() {return MLTC(u"Language", DE, u"Sprache", FR, u"Langue", IT, u"Lingua", SP, u"Idioma", PO, u"Linguagem", PL, u"Język", RU, u"Язык", JP, u"言語", KO, u"언어", CN, u"语言", TH, u"ภาษา");}
CChar* TLarge(TRANS_FORM form) {return MLTC(u"Large" , DE, u"Groß", FR, u"Grand", IT, u"Grande", SP, u"Grande", PO, u"Grande", PL, (form==TF_MALE) ? u"Duży" : (form==TF_FEMALE) ? u"Duża" : u"Duże", RU, u"Большой", JP, u"大きい", KO, u"크기가 큰", CN, u"大", TH, u"ใหญ่");}
CChar* TLearnedSpell() {return MLTC(u"Learned Spell", DE, u"Gelernter Zauber", FR, u"Sort Appris", IT, u"Incantesimo Appreso", SP, u"Hechizo Aprendido", PO, u"Feitiço Aprendido", PL, u"Poznano Czar", RU, u"Выученное Заклинание", JP, u"学んだ呪文", KO, u"배운 주문", CN, u"学习拼写", TH, u"เรียนรู้คาถา");}
CChar* TLeft() {return MLTC(u"Left", DE, u"Links", FR, u"Gauche", IT, u"Sinistra", SP, u"Izquierdo", PO, u"Esquerdo", PL, u"Lewo", RU, u"Осталось", JP, u"左", KO, u"왼쪽", CN, u"剩下", TH, u"ซ้าย");}
CChar* TLevel() {return MLTC(u"Level", DE, u"Stufe", FR, u"Niveau", IT, u"Livello", SP, u"Nivel", PO, u"Nível", PL, u"Poziom", RU, u"Уровень", JP, u"レベル", KO, u"수준", CN, u"等级", TH, u"ระดับ");}
CChar* TLevels() {return MLTC(u"Levels", DE, u"Ebenen", FR, u"Niveaux", IT, u"Livelli", SP, u"Niveles", PO, u"Níveis", PL, u"Poziomy", RU, u"Уровни", JP, u"レベル", KO, u"레벨", CN, u"级别", TH, u"ระดับ");}
CChar* TLoading() {return MLTC(u"Loading", DE, u"Wird geladen", FR, u"Chargement", IT, u"Attesa", SP, u"Cargando", PO, u"Carregando", PL, u"Ładuję", RU, u"Загрузка", JP, u"読み込み中", KO, u"로딩 중", CN, u"正在加载", TH, u"กำลังโหลด");}
CChar* TLocked() {return MLTC(u"Locked", DE, u"Gesperrt", FR, u"Fermé à clé", IT, u"Bloccato", SP, u"Bloqueado", PO, u"Bloqueado", PL, u"Zamknięte", RU, u"Заблокировано", JP, u"ロック済み", KO, u"잠김", CN, u"锁定", TH, u"ถูกล็อค");}
CChar* TTouchRotation() {return MLTC(u"Touch Rotation", DE, u"Tippen Sie auf Drehung", FR, u"Tactile Rotation", IT, u"Toccare Rotazione", SP, u"Táctil Rotación", PO, u"Rotação de Toque", PL, u"Dotykowy Obrót", RU, u"Сенсорное Вращение", JP, u"タッチローテーション", KO, u"터치 회전", CN, u"触摸旋转", TH, u"หมุนสัมผัส");}
CChar* TLow(TRANS_FORM form) {return MLTC(u"Low", DE, u"Niedrig", FR, u"Meugler", IT, u"Basso", SP, u"Bajo", PO, u"Baixo", PL, (form==TF_MALE) ? u"Niski" : (form==TF_FEMALE) ? u"Niska" : u"Niskie", RU, u"Низкий", JP, u"低い", KO, u"낮은", CN, u"低的", TH, u"ต่ำ");}
CChar* TMace() {return MLTC(u"Mace", DE, u"Keule", FR, u"Masse", IT, u"Mazza", SP, u"Mazo", PO, u"Maça", PL, u"Buzdygan", RU, u"Булава", JP, u"メース", KO, u"메이스", CN, u"锤", TH, u"กระบอง");}
CChar* TMagic() {return MLTC(u"Magic", DE, u"Magie", FR, u"Magie", IT, u"Magia", SP, u"Magia", PO, u"Magia", PL, u"Magia", RU, u"Магия", JP, u"魔法", KO, u"마법", CN, u"魔法", TH, u"มายากล");}
CChar* TMap() {return MLTC(u"Map", DE, u"Karte", FR, u"Carte", IT, u"Mappa", SP, u"Mapa", PO, u"Mapa", PL, u"Mapa", RU, u"Карта", JP, u"地図", KO, u"지도", CN, u"地图", TH, u"แผนที่");}
CChar* TMana() {return MLTC(u"Mana", DE, u"Mana", FR, u"Mana", IT, u"Mana", SP, u"Maná", PO, u"Mana", PL, u"Mana", RU, u"Мана", JP, u"マナ", KO, u"마나", CN, u"法力", TH, u"มานะ");}
CChar* TManaPotion() {return MLTC(u"Mana Potion", DE, u"Manatrank", FR, u"Potion de Mana", IT, u"Pozione di Mana", SP, u"Poción de Maná", PO, u"Poção de Mana", PL, u"Eliksir Mana", RU, u"Зелье Маны", JP, u"マナポーション", KO, u"마나 물약", CN, u"法力药水", TH, u"น้ำยามานา");}
CChar* TMasterVolume() {return MLTC(u"Master Volume", DE, u"Master Lautstärke", FR, u"Volume Principal", IT, u"Volume Principale", SP, u"Volumen Principal", PO, u"Volume Principal", PL, u"Głośność", RU, u"Мастер Громкость", JP, u"マスターボリューム", KO, u"마스터 볼륨", CN, u"主音量", TH, u"ปริมาณหลัก");}
CChar* TMayan() {return MLTC(u"Mayan", DE, u"Maya", FR, u"Maya", IT, u"Maya", SP, u"Maya", PO, u"Maia", PL, u"Majowie", RU, u"Майя", JP, u"マヤ", KO, u"마야", CN, u"玛雅", TH, u"มายัน");}
CChar* TMaxLights() {return MLTC(u"Max Lights", DE, u"Lichter Begrenzen", FR, u"Feux de Limite", IT, u"Limite di Luci", SP, u"Luces de Límite", PO, u"Luzes de Limite", PL, u"Limit Świateł", RU, u"Ограничение Огни", JP, u"ライトを制限する", KO, u"제한 조명", CN, u"限位灯", TH, u"ไฟจำกัด");}
CChar* TMedium(TRANS_FORM form) {return MLTC(u"Medium", DE, u"Mittel", FR, u"Moyen", IT, u"Medio", SP, u"Medio", PO, u"Médio", PL, (form==TF_MALE) ? u"Średni" : (form==TF_FEMALE) ? u"Średnia" : u"Średnie", RU, u"Середина", JP, u"中くらい", KO, u"중간", CN, u"中等的", TH, u"ปานกลาง");}
CChar* TMenu() {return MLTC(u"Menu", DE, u"Hauptmenü", FR, u"Menu", IT, u"Menù", SP, u"Menú", PO, u"Cardápio", PL, u"Menu", RU, u"Меню", JP, u"メニュー", KO, u"메뉴", CN, u"菜单", TH, u"เมนู");}
CChar* TMessage() {return MLTC(u"Message", DE, u"Nachricht", FR, u"Message", IT, u"Messaggio", SP, u"Mensaje", PO, u"Mensagem", PL, u"Wiadomość", RU, u"Сообщение", JP, u"メッセージ", KO, u"메시지", CN, u"信息", TH, u"ข้อความ");}
CChar* TMonster() {return MLTC(u"Monster", DE, u"Monster", FR, u"Monstre", IT, u"Mostro", SP, u"Monstruo", PO, u"Monstro", PL, u"Potwór", RU, u"Монстр", JP, u"モンスター", KO, u"괴물", CN, u"怪物", TH, u"สัตว์ประหลาด");}
CChar* TMonsters() {return MLTC(u"Monsters", DE, u"Monster", FR, u"Monstres", IT, u"Mostri", SP, u"Monstruos", PO, u"Monstros", PL, u"Potwory", RU, u"Монстры", JP, u"モンスター", KO, u"몬스터", CN, u"怪物", TH, u"สัตว์ประหลาด");}
CChar* TMoreManaNeeded() {return MLTC(u"More Mana needed", DE, u"Mehr Mana benötigt", FR, u"Plus de Mana nécessaire", IT, u"Più Mana necessario", SP, u"Se necesita más Maná", PO, u"Mais Mana necessária", PL, u"Potrzeba więcej Many", RU, u"Нужно больше Маны", JP, u"もっとマナが必要", KO, u"더 많은 마나가 필요합니다", CN, u"需要更多法力", TH, u"ต้องการมานามากขึ้น");}
CChar* TMotionBlur() {return MLTC(u"Motion Blur", DE, u"Bewegungsunschärfe", FR, u"Flou Cinétique", IT, u"Mosso", SP, u"Desenfoque de Movimiento", PO, u"Desfoque de Movimento", PL, u"Rozmycie w Ruchu", RU, u"Шевелёнка", JP, u"モーションブラー", KO, u"모션 블러", CN, u"動態模糊", TH, u"โมชั่นเบลอ");}
CChar* TMotionBlurIntensity() {return MLTC(u"Motion Blur Intensity", DE, u"Unschärfeintensität", FR, u"Intensité du Flou", IT, u"Intensità Sfocatura", SP, u"Intensidad de Desenfoque", PO, u"Intensidade do Desfoque", PL, u"Intensywność Rozmycia", RU, u"Интенсивность Размытия", JP, u"モーションブラーの強度", KO, u"모션 블러 강도", CN, u"运动模糊强度", TH, u"ความเข้มของภาพเบลอ");}
CChar* TMouseInvert() {return MLTC(u"Mouse Invert", DE, u"Maus Umkehren", FR, u"Inverser la Souris", IT, u"Inversione del Mouse", SP, u"Ratón Invertir", PO, u"Inversão do Mouse", PL, u"Mysz Odwrócona", RU, u"Инверсия Мыши", JP, u"マウス反転", KO, u"마우스 반전", CN, u"鼠标反转", TH, u"สลับเมาส์");}
CChar* TMouseSensitivity() {return MLTC(u"Mouse Sensitivity", DE, u"Maus Empfindlichkeit", FR, u"Sensibilité de la Souris", IT, u"Sensibilità del Mouse", SP, u"Sensibilidad del Ratón", PO, u"Sensibilidade do Mouse", PL, u"Czułość Myszy", RU, u"Чувствительность Мыши", JP, u"マウス感度", KO, u"마우스 감도", CN, u"鼠标灵敏度", TH, u"ความไวของเมาส์");}
CChar* TMove() {return MLTC(u"Move", DE, u"Verschieben", FR, u"Déplacer", IT, u"Sposta", SP, u"Mover", PO, u"Mover", PL, u"Przenieś", RU, u"Переместить", JP, u"を動かす", KO, u"이동", CN, u"移动", TH, u"ย้าย");}
CChar* TMoveBack() {return MLTC(u"Move Back", DE, u"Zurückgehen", FR, u"Reculer", IT, u"Andare indietro", SP, u"Retroceder", PO, u"Voltar", PL, u"Idź do tyłu", RU, u"Вернуться назад", JP, u"戻ってくる", KO, u"뒤로가", CN, u"向后移动", TH, u"ถอยหลังไป");}
CChar* TMoveForward() {return MLTC(u"Move Forward", DE, u"Bewegen Sie sich vorwärts", FR, u"Avance", IT, u"Vai avanti", SP, u"Avanzar", PO, u"Siga em frente", PL, u"Idź naprzód", RU, u"Двигаться вперед", JP, u"前進する", KO, u"앞으로가", CN, u"前进", TH, u"เดินหน้า");}
CChar* TMoveLeft() {return MLTC(u"Move Left", DE, u"Geh nach links", FR, u"Se déplacer à gauche", IT, u"Muovere a sinistra", SP, u"Mover hacia la izquierda", PO, u"Mova para a esquerda", PL, u"Idź w lewo", RU, u"Двигай влево", JP, u"左に移動", KO, u"왼쪽으로 이동", CN, u"向左移动", TH, u"เลื่อนไปทางซ้าย");}
CChar* TMoveRight() {return MLTC(u"Move Right", DE, u"Nach rechts bewegen", FR, u"Déplacer vers la droite", IT, u"Vai a destra", SP, u"Mover a la derecha", PO, u"Mover para a direita", PL, u"Idź w prawo", RU, u"Переместить вправо", JP, u"右に動く", KO, u"오른쪽으로 이동해라", CN, u"向右移", TH, u"เลื่อนไปทางขวา");}
CChar* TMultiSampling() {return MLTC(u"Multi Sampling", DE, u"Multi Sampling (MSAA)", FR, u"Multi Sampling (MSAA)", IT, u"Multi Sampling (MSAA)", SP, u"Muestreo Múltiple (MSAA)", PO, u"Multi Sampling (MSAA)", PL, u"Multipróbkowanie (MSAA)", RU, u"Мультисэмплинг (MSAA)", JP, u"マルチサンプリング (MSAA)", KO, u"멀티 샘플링 (MSAA)", CN, u"多重采样 (MSAA)", TH, u"สุ่มตัวอย่างหลายตัว (MSAA)");}
CChar* TMusicVolume() {return MLTC(u"Music Volume", DE, u"Musiklautstärke", FR, u"Volume de la Musique", IT, u"Volume della Musica", SP, u"Volumen de la Música", PO, u"Volume da Música", PL, u"Głośność Muzyki", RU, u"Громкость Музыки", JP, u"ミュージックボリューム", KO, u"음악 볼륨", CN, u"音乐音量", TH, u"ระดับเสียงเพลง");}
CChar* TMute() {return MLTC(u"Mute", DE, u"Stumm", FR, u"Muet", IT, u"Muto", SP, u"Mudo", PO, u"Mudo", PL, u"Wycisz", RU, u"Тишина", JP, u"ミュート", KO, u"무음", CN, u"静音", TH, u"ปิดเสียง");}
CChar* TMyMaps() {return MLTC(u"My Maps", DE, u"Meine Karten", FR, u"Mes Cartes", IT, u"Le mie Mappe", SP, u"Mis Mapas", PO, u"Meus Mapas", PL, u"Moje Mapy", RU, u"Мои Карты", JP, u"マイマップ", KO, u"내 지도", CN, u"我的地图", TH, u"แผนที่ของฉัน");}
CChar* TName() {return MLTC(u"Name", DE, u"Name", FR, u"Nom", IT, u"Nome", SP, u"Nombre", PO, u"Nome", PL, u"Nazwa", RU, u"Имя", JP, u"名前", KO, u"이름", CN, u"姓名", TH, u"ชื่อ");}
CChar* TNeedMoreGems() {return MLTC(u"Need More Gems", DE, u"Benötigen Sie mehr Edelsteine", FR, u"Besoin de Plus de Gemmes", IT, u"Hai Bisogno di Più Gemme", SP, u"Necesito Más Gemas", PO, u"Precisa de Mais Joias", PL, u"Potrzebujesz Więcej Klejnotów", RU, u"Нужно больше Кристаллов", JP, u"もっと宝石が必要", KO, u"더 많은 보석이 필요합니다", CN, u"需要更多宝石", TH, u"ต้องการอัญมณีเพิ่มเติม");}
CChar* TNeedMoreGold() {return MLTC(u"Need More Gold", DE, u"Benötigen Sie mehr Gold", FR, u"Besoin de Plus d'Or", IT, u"Hai Bisogno di Più Oro", SP, u"Necesito Más Oro", PO, u"Precisa de Mais Ouro", PL, u"Potrzeba Więcej Złota", RU, u"Нужно больше Золота", JP, u"もっと金が必要", KO, u"더 많은 금이 필요합니다", CN, u"需要更多黄金", TH, u"ต้องการทองเพิ่ม");}
CChar* TNeedMoreMana() {return MLTC(u"Need More Mana", DE, u"Brauche mehr Mana", FR, u"Besoin de Plus de Mana", IT, u"Hai Bisogno di Più Mana", SP, u"Necesito Más Maná", PO, u"Precisa de Mais Mana", PL, u"Potrzeba Więcej Many", RU, u"Нужно больше Маны", JP, u"もっとマナが必要", KO, u"더 많은 마나가 필요합니다", CN, u"需要更多法力", TH, u"ต้องการมานาเพิ่มเติม");}
CChar* TNeedMoreTime() {return MLTC(u"Need More Time", DE, u"Brauche mehr Zeit", FR, u"Besoin de Plus de Temps", IT, u"Ho Bisogno di Più Tempo", SP, u"Necesito Mas Tiempo", PO, u"Preciso de Mais Tempo", PL, u"Potrzeba Więcej Czasu", RU, u"Нужно больше Времени", JP, u"もっと時間が必要です", KO, u"시간이 더 필요하다", CN, u"需要更多时间", TH, u"ต้องการเวลามากกว่านี้");}
CChar* TNew() {return MLTC(u"New", DE, u"Neu", FR, u"Nouveau", IT, u"Nuovo", SP, u"Nuevo", PO, u"Novo", PL, u"Nowy", RU, u"Новый", JP, u"新しい", KO, u"새로운", CN, u"新的", TH, u"ใหม่");}
CChar* TNewMap() {return MLTC(u"New Map", DE, u"Neue Karte", FR, u"Nouvelle Carte", IT, u"Nuova Mappa", SP, u"Nuevo Mapa", PO, u"Novo Mapa", PL, u"Nowa Mapa", RU, u"Новая Карта", JP, u"新しいマップ", KO, u"새 지도", CN, u"新地图", TH, u"แผนที่ใหม่");}
CChar* TNextItem() {return MLTC(u"Next Item", DE, u"Nächstes Objekt", FR, u"Prochain Point", IT, u"Articolo Successivo", SP, u"Proximo Articulo", PO, u"Próximo Item", PL, u"Następny Przedmiot", RU, u"Следующий Элемент", JP, u"次のアイテム", KO, u"다음 항목", CN, u"下一项", TH, u"รายการถัดไป");}
CChar* TNextSpell() {return MLTC(u"Next Spell", DE, u"Nächster Zauber", FR, u"Sort Suivant", IT, u"Prossimo Incantesimo", SP, u"Siguiente Hechizo", PO, u"Próximo Feitiço", PL, u"Następny Czar", RU, u"Следующее Заклинание", JP, u"次の呪文", KO, u"다음 주문", CN, u"下一个法术", TH, u"คาถาถัดไป");}
CChar* TNo() {return MLTC(u"No", DE, u"Nein", FR, u"Non", IT, u"No", SP, u"No", PO, u"Não", PL, u"Nie", RU, u"Нет", JP, u"番号", KO, u"아니요", CN, u"不", TH, u"ไม่");}
CChar* TNoAmmo() {return MLTC(u"No Ammo", DE, u"Keine Munition", FR, u"Pas de Munitions", IT, u"Nessuna Munizione", SP, u"Sin Municiones", PO, u"Sem Munição", PL, u"Brak Amunicji", RU, u"Нет Боеприпасов", JP, u"弾薬なし", KO, u"탄약 없음", CN, u"没有弹药", TH, u"ไม่มีกระสุน");}
CChar* TNoHeroSelected() {return MLTC(u"No Hero selected", DE, u"Kein Held ausgewählt", FR, u"Aucun héros sélectionné", IT, u"Nessun eroe selezionato", SP, u"Ningún héroe seleccionado", PO, u"Nenhum herói selecionado", PL, u"Nie wybrano bohatera", RU, u"Герой не выбран", JP, u"ヒーローが選択されていません", KO, u"선택한 영웅이 없습니다", CN, u"未选择英雄", TH, u"ไม่ได้เลือกฮีโร่");}
CChar* TNoMapSelected() {return MLTC(u"No Map selected", DE, u"Keine Karte ausgewählt", FR, u"Aucune carte sélectionnée", IT, u"Nessuna mappa selezionata", SP, u"Ningún mapa seleccionado", PO, u"Nenhum mapa selecionado", PL, u"Nie wybrano mapy", RU, u"Карта не выбрана", JP, u"マップが選択されていません", KO, u"선택한 지도 없음", CN, u"未选择地图", TH, u"ไม่ได้เลือกแผนที่");}
CChar* TNone(TRANS_FORM form) {return MLTC(u"None", DE, u"Keiner", FR, (form==TF_FEMALE) ? u"Aucune" : u"Aucun", IT, u"Nessuno", SP, (form==TF_FEMALE) ? u"Ninguna" : u"Ninguno", PO, u"Nenhum", PL, (form==TF_MALE) ? u"Żadny" : (form==TF_FEMALE) ? u"Żadna" : u"Żadne", RU, u"Никто", JP, u"なし", KO, u"없음", CN, u"没有", TH, u"ไม่มี");}
CChar* TNormal(TRANS_FORM form) {return MLTC(u"Normal", DE, u"Normal", FR, u"Normal", IT, u"Normale", SP, u"Normal", PO, u"Normal", PL, (form==TF_MALE) ? u"Normalny" : (form==TF_FEMALE) ? u"Normalna" : u"Normalne", RU, u"Обычный", JP, u"普通", KO, u"정상", CN, u"普通的", TH, u"ปกติ");}
CChar* TObjects() {return MLTC(u"Objects", DE, u"Objekte", FR, u"Objets", IT, u"Oggetti", SP, u"Objetos", PO, u"Objetos", PL, u"Obiekty", RU, u"Объекты", JP, u"オブジェクト", KO, u"사물", CN, u"对象", TH, u"วัตถุ");}
CChar* TOilBomb() {return MLTC(u"Oil Bomb", DE, u"Ölbombe", FR, u"Bombe à Huile", IT, u"Bomba Petrolifera", SP, u"Bomba de Aceite", PO, u"Bomba de Óleo", PL, u"Bomba Olejowa", RU, u"Масляная Бомба", JP, u"オイルボム", KO, u"기름폭탄", CN, u"石油炸弹", TH, u"ระเบิดน้ำมัน");}
CChar* TOnServer() {return MLTC(u"On Server", DE, u"Auf dem Server", FR, u"Sur le Serveur", IT, u"Sul Server", SP, u"En el Servidor", PO, u"No Servidor", PL, u"Na Serwerze", RU, u"На Сервере", JP, u"サーバー上", KO, u"서버에서", CN, u"在服务器上", TH, u"บนเซิร์ฟเวอร์");}
CChar* TOpen() {return MLTC(u"Open", DE, u"Öffne", FR, u"Ouvre", IT, u"Apri", SP, u"Abre", PO, u"Abra", PL, u"Otwórz", RU, u"Открыть", JP, u"開く", KO, u"열다", CN, u"打开", TH, u"เปิด");}
CChar* TOptions() {return MLTC(u"Options", DE, u"Optionen", FR, u"Choix", IT, u"Opzioni", SP, u"Opciones", PO, u"Opções", PL, u"Opcje", RU, u"Опции", JP, u"オプション", KO, u"옵션", CN, u"选项", TH, u"ตัวเลือก");}
CChar* TPainted() {return MLTC(u"Painted", DE, u"Gemalt", FR, u"Peint", IT, u"Dipinto", SP, u"Pintado", PO, u"Pintado", PL, u"Malowany", RU, u"Окрашенный", JP, u"描きました", KO, u"그린", CN, u"绘", TH, u"ทาสี");}
CChar* TPetLevelUp() {return MLTC(u"Pet Level Up", DE, u"Pet Level auf", FR, u"Monter le niveau du familier", IT, u"Animale salire di livello", SP, u"Mascota subir de nivel", PO, u"Subir de nível animal", PL, u"Zwierzątko uzyskało Poziom", RU, u"Повышение уровня питомца", JP, u"ペットのレベルアップ", KO, u"펫 레벨업", CN, u"宠物升级", TH, u"สัตว์เลี้ยงเลเวลอัพ");}
CChar* TPetScreen() {return MLTC(u"Pet Screen", DE, u"Pet Bildschirm", FR, u"Écran pour animaux", IT, u"Schermo per animali", SP, u"Pantalla de mascotas", PO, u"Tela para animais de estimação", PL, u"Ekran Zwierzątka", RU, u"Экран для домашних животных", JP, u"ペットスクリーン", KO, u"펫 스크린", CN, u"宠物屏风", TH, u"หน้าจอสัตว์เลี้ยง");}
CChar* TPets() {return MLTC(u"Pets", DE, u"Haustiere", FR, u"Animaux", IT, u"Animali", SP, u"Mascotas", PO, u"Animais", PL, u"Zwierzątka", RU, u"Любимец", JP, u"ペット", KO, u"애완동물", CN, u"宠物", TH, u"สัตว์เลี้ยง");}
CChar* TPickedUp() {return MLTC(u"Picked Up", DE, u"Abgeholt", FR, u"Ramassé", IT, u"Raccolto", SP, u"Recogido", PO, u"Pegou", PL, u"Pobrano"/*"Zebrano"*/, RU, u"Поднял", JP, u"拾った", KO, u"픽업", CN, u"已接", TH, u"หยิบขึ้น");}
CChar* TPit() {return MLTC(u"Pit", DE, u"Grube", FR, u"Fosse", IT, u"Fossa", SP, u"Foso", PO, u"Poço", PL, u"Dół", RU, u"Яма", JP, u"ピット", KO, u"피트", CN, u"坑", TH, u"หลุม");}
CChar* TPixelDensity() {return MLTC(u"Pixel Density", DE, u"Pixeldichte", FR, u"Densité de Pixels", IT, u"Densità di Pixel", SP, u"Densidad de Pixeles", PO, u"Densidade de Pixels", PL, u"Gęstość Pikseli", RU, u"Плотность Пикселей", JP, u"画素密度", KO, u"픽셀 밀도", CN, u"像素密度", TH, u"ความหนาแน่นของพิกเซล");}
CChar* TPlaceInsert() {return MLTC(u"Place", DE, u"Platzieren", FR, u"Placer", IT, u"Mettere", SP, u"Colocar", PO, u"Colocar", PL, u"Wstaw", RU, u"Поместите", JP, u"置く", KO, u"놓다", CN, u"放置", TH, u"วาง");}
CChar* TPlay() {return MLTC(u"Play", DE, u"Spiel", FR, u"Jouer", IT, u"Giocare", SP, u"Jugar", PO, u"Jogar", PL, u"Graj", RU, u"Играть", JP, u"遊ぶ", KO, u"놀다", CN, u"玩", TH, u"เล่น");}
CChar* TPlayer() {return MLTC(u"Player", DE, u"Spieler", FR, u"Joueur", IT, u"Giocatore", SP, u"Jugador", PO, u"Jogador", PL, u"Gracz", RU, u"Игрок", JP, u"プレーヤー", KO, u"플레이어", CN, u"播放器", TH, u"ผู้เล่น");}
CChar* TPlayerLevel() {return MLTC(u"Player Level", DE, u"Spielerlevel", FR, u"Niveau du Joueur", IT, u"Livello Giocatore", SP, u"Nivel de Jugador", PO, u"Nível do Jogador", PL, u"Poziom Gracza", RU, u"Уровень Игрока", JP, u"プレイヤーレベル", KO, u"플레이어 레벨", CN, u"玩家等级", TH, u"ระดับผู้เล่น");}
CChar* TPlayerLevelUp() {return MLTC(u"Player Level Up", DE, u"Spielerlevel aufsteigen", FR, u"Niveau supérieur du joueur", IT, u"Livello del giocatore", SP, u"Jugador subir de nivel", PO, u"Subir de nível do jogador", PL, u"Gracz uzyskał Poziom", RU, u"Повышение уровня игрока", JP, u"プレイヤーレベルアップ", KO, u"플레이어 레벨업", CN, u"玩家等级提升", TH, u"ผู้เล่นระดับขึ้น");}
CChar* TPoints() {return MLTC(u"Points", DE, u"Punkte", FR, u"Points", IT, u"Punti", SP, u"Puntos", PO, u"Pontos", PL, u"Punkty", RU, u"Точки", JP, u"ポイント", KO, u"포인트들", CN, u"积分", TH, u"คะแนน");}
CChar* TPoisonBomb() {return MLTC(u"Poison Bomb", DE, u"Giftbombe", FR, u"Bombe Empoisonnée", IT, u"Bomba Velenosa", SP, u"Bomba de Veneno", PO, u"Bomba Venenosa", PL, u"Trująca Bomba", RU, u"Ядовитая Бомба", JP, u"毒爆弾", KO, u"독 폭탄", CN, u"毒弹", TH, u"ระเบิดพิษ");}
CChar* TPoisonCloud() {return MLTC(u"Poison Cloud", DE, u"Giftwolke", FR, u"Nuage Empoisonné", IT, u"Nuvola Velenosa", SP, u"Nube de Veneno", PO, u"Nuvem Venenosa", PL, u"Trująca Chmura", RU, u"Ядовитое Облако", JP, u"ポイズンクラウド", KO, u"포이즌 클라우드", CN, u"毒云", TH, u"เมฆพิษ");}
CChar* TPolearm() {return MLTC(u"Polearm", DE, u"Stangenwaffe", FR, u"Arme d'hast", IT, u"Alabarda", SP, u"Arma de Asta", PO, u"Pistola", PL, u"Halabarda", RU, u"Древковое Оружие", JP, u"ポールアーム", KO, u"폴암", CN, u"长柄武器", TH, u"โพลอาร์ม");}
CChar* TPotion() {return MLTC(u"Potion", DE, u"Trank", FR, u"Potion", IT, u"Pozione", SP, u"Poción", PO, u"Poção", PL, u"Eliksir", RU, u"Зелье", JP, u"薬", KO, u"물약", CN, u"药水", TH, u"โพชั่น");}
Str    TPoweredBy(CChar *name) {return MLT(S+"Powered by "+name, DE, S+u"Unterstützt von "+name, FR, S+u"Propulsé par "+name, IT, S+u"Alimentato da "+name, SP, S+u"Desarrollado por "+name, PO, S+u"Desenvolvido por "+name, PL, S+u"Zasilane przez "+name, RU, S+u"Создано "+name, JP, S+name+u" を搭載", KO, S+name+u" 제공", CN, S+u"由 "+name+u" 提供支持", TH, S+u"ขับเคลื่อนโดย "+name);}
CChar* TPress() {return MLTC(u"Press", DE, u"Drücken", FR, u"Presse", IT, u"Stampa", SP, u"Prensa", PO, u"Pressione", PL, u"Wciśnij", RU, u"Нажмите", JP, u"押す", KO, u"누르다", CN, u"按", TH, u"กด");}
CChar* TPreviousItem() {return MLTC(u"Previous Item", DE, u"Vorheriges Objekt", FR, u"Article Précédent", IT, u"Articolo Precedente", SP, u"Artículo Anterior", PO, u"Item Anterior", PL, u"Poprzedni Przedmiot", RU, u"Предыдущий Элемент", JP, u"前のアイテム", KO, u"이전 항목", CN, u"上一项", TH, u"รายการก่อนหน้า");}
CChar* TPreviousSpell() {return MLTC(u"Previous Spell", DE, u"Vorheriger Zauber", FR, u"Sort Précédent", IT, u"Incantesimo Precedente", SP, u"Hechizo Anterior", PO, u"Feitiço Anterior", PL, u"Poprzedni Czar", RU, u"Предыдущее Заклинание", JP, u"前の呪文", KO, u"이전 주문", CN, u"上一个法术", TH, u"คาถาก่อนหน้า");}
CChar* TPrison() {return MLTC(u"Prison", DE, u"Gefängnis", FR, u"Prison", IT, u"Prigione", SP, u"Prisión", PO, u"Prisão", PL, u"Więzienie", RU, u"Тюрьма", JP, u"刑務所", KO, u"감옥", CN, u"监狱", TH, u"คุก");}
CChar* TProp() {return MLTC(u"Prop", DE, u"Stütze", FR, u"Soutenir", IT, u"Puntello", SP, u"Apuntalar", PO, u"Suporte", PL, u"Rekwizyt", RU, u"Опора", JP, u"プロップ", KO, u"소품", CN, u"支柱", TH, u"พร็อพ");}
CChar* TPutOnYourHeadset() {return MLTC(u"Please put on your headset", DE, u"Bitte setzen Sie Ihr VR Set auf", FR, u"Veuillez mettre votre ensemble VR", IT, u"Per favore indossa il tuo set VR", SP, u"Por favor, póngase su equipo de realidad virtual", PO, u"Por favor, coloque seu conjunto de RV", PL, u"Proszę założyć zestaw VR", RU, u"Пожалуйста, наденьте свой комплект виртуальной реальности", JP, u"VRセットを装着してください", KO, u"VR 세트를 착용하세요", CN, u"请戴上你的 VR 设备", TH, u"กรุณาใส่ชุด VR ของคุณ");}
CChar* TPyramid() {return MLTC(u"Pyramid", DE, u"Pyramide", FR, u"Pyramide", IT, u"Piramide", SP, u"Pirámide", PO, u"Pirâmide", PL, u"Piramida", RU, u"Пирамида", JP, u"ピラミッド", KO, u"피라미드", CN, u"金字塔", TH, u"พีระมิด");}
CChar* TQuiver() {return MLTC(u"Quiver", DE, u"Köcher", FR, u"Carquois", IT, u"Faretra", SP, u"Carcaj", PO, u"Aljava", PL, u"Kołczan", RU, u"Колчан", JP, u"箙", KO, u"동개", CN, u"箭囊", TH, u"สั่น");}
CChar* TRagePotion() {return MLTC(u"Rage Potion", DE, u"Wut Trank", FR, u"Potion de Rage", IT, u"Pozione di Rabbia", SP, u"Poción de Ira", PO, u"Poção de Fúria", PL, u"Eliksir Szału", RU, u"Зелье Ярости", JP, u"レイジポーション", KO, u"분노의 물약", CN, u"愤怒药水", TH, u"ยาความโกรธ");}
CChar* TRandom(TRANS_FORM form) {return MLTC(u"Random", DE, u"Zufällig", FR, u"Aléatoire", IT, u"Casuale", SP, u"Aleatorio", PO, u"Aleatório", PL, (form==TF_MALE) ? u"Losowy" : (form==TF_FEMALE) ? u"Losowa" : u"Losowe", RU, u"Случайный", JP, u"ランダム", KO, u"무작위의", CN, u"随机的", TH, u"สุ่ม");}
CChar* TRanking() {return MLTC(u"Ranking", DE, u"Rangfolge", FR, u"Classement", IT, u"Punto", SP, u"Puntaje", PO, u"Pontuação", PL, u"Ranking", RU, u"Рейтинг", JP, u"ランキング", KO, u"순위", CN, u"排行", TH, u"อันดับ");}
CChar* TRead() {return MLTC(u"Read", DE, u"Lies", FR, u"Lis", IT, u"Leggi", SP, u"Lee", PO, u"Leia", PL, u"Przeczytaj", RU, u"Прочитай", JP, u"読んだ", KO, u"읽다", CN, u"读", TH, u"อ่าน");}
CChar* TRealistic() {return MLTC(u"Realistic", DE, u"Realistisch", FR, u"Réaliste", IT, u"Realistico", SP, u"Realista", PO, u"Realista", PL, u"Realistyczny", RU, u"Реалистичный", JP, u"リアル", KO, u"현실적", CN, u"实际的", TH, u"เหมือนจริง");}
CChar* TRecenterVR() {return MLTC(u"Recenter VR", DE, u"VR neu Zentrieren", FR, u"VR plus récente", IT, u"VR più recente", SP, u"VR Reciente", PO, u"RV mais recente", PL, u"Wycentruj VR", RU, u"Рецентрировать VR", JP, u"最近のVR", KO, u"최근 VR", CN, u"中心VR", TH, u"ล่าสุดVR");}
CChar* TRemove() {return MLTC(u"Remove", DE, u"Entfernen", FR, u"Éliminer", IT, u"Rimuovere", SP, u"Remover", PO, u"Remover", PL, u"Usuń", RU, u"Удалять", JP, u"削除する", KO, u"제거하다", CN, u"消除", TH, u"ลบ");}
CChar* TRename() {return MLTC(u"Rename", DE, u"Umbenennen", FR, u"Renommer", IT, u"Rinominare", SP, u"Rebautizar", PO, u"Renomear", PL, u"Zmień Nazwę", RU, u"Переименовать", JP, u"名前を変更", KO, u"이름 바꾸기", CN, u"改名", TH, u"เปลี่ยนชื่อ");}
CChar* TResolution() {return MLTC(u"Resolution", DE, u"Auflösung", FR, u"Résolution", IT, u"Risoluzione", SP, u"Resolución", PO, u"Resolução", PL, u"Rozdzielczość", RU, u"Разрешение", JP, u"画面の解像度", KO, u"화면 해상도", CN, u"屏幕分辨率", TH, u"ความละเอียดหน้าจอ");}
CChar* TRestart() {return MLTC(u"Restart", DE, u"Neu starten", FR, u"Redémarrage", IT, u"Ricomincia", SP, u"Reiniciar", PO, u"Reiniciar", PL, u"Zrestartuj", RU, u"Начать сначала", JP, u"再起動", KO, u"재시작", CN, u"重新开始", TH, u"เริ่มต้นใหม่");}
CChar* TRevive() {return MLTC(u"Revive", DE, u"Beleben", FR, u"Relancer", IT, u"Rianima", SP, u"Reanimar", PO, u"Reviver", PL, u"Wskrześ", RU, u"Возродить", JP, u"復活する", KO, u"소생", CN, u"复活", TH, u"ฟื้นคืนชีพ");}
CChar* TRevived() {return MLTC(u"Revived", DE, u"Wiederbelebt", FR, u"Ressuscité", IT, u"Rianimato", SP, u"Revivido", PO, u"Reviveu", PL, u"Wskrzeszono", RU, u"Возрожденный", JP, u"復活", KO, u"되살아난", CN, u"复活", TH, u"ฟื้นคืนชีพ");}
CChar* TRight() {return MLTC(u"Right", DE, u"Rechts", FR, u"Droit", IT, u"Destro", SP, u"Derecho", PO, u"Certo", PL, u"Prawo", RU, u"Верно", JP, u"右", KO, u"오른쪽", CN, u"正确的", TH, u"ใช่ไหม");}
CChar* TRing() {return MLTC(u"Ring", DE, u"Ringe", FR, u"Anneau", IT, u"Squillare", SP, u"Anillo", PO, u"Anel", PL, u"Pierścień", RU, u"Звенеть", JP, u"指輪", KO, u"반지", CN, u"戒指", TH, u"แหวน");}
CChar* TRooms() {return MLTC(u"Rooms", DE, u"Räume", FR, u"Pièces", IT, u"Camere", SP, u"Habitaciones", PO, u"Quartos", PL, u"Pokoje", RU, u"Номера", JP, u"部屋", KO, u"객실", CN, u"房间", TH, u"ห้อง");}
CChar* TScorpions() {return MLTC(u"Scorpions", DE, u"Skorpione", FR, u"Scorpions", IT, u"Scorpioni", SP, u"Escorpiones", PO, u"Escorpiões", PL, u"Skorpiony", RU, u"Скорпионы", JP, u"スコーピオンズ", KO, u"전갈", CN, u"蝎子", TH, u"แมงป่อง");}
CChar* TScythe() {return MLTC(u"Scythe", DE, u"Sense", FR, u"Faux", IT, u"Falce", SP, u"Guadaña", PO, u"Foice", PL, u"Kosa", RU, u"Коса", JP, u"サイス", KO, u"큰 낫", CN, u"镰", TH, u"เคียว");}
CChar* TSecretWall() {return MLTC(u"Secret Wall", DE, u"Geheime Wand", FR, u"Mur Secret", IT, u"Muro Segreto", SP, u"Muro Secreto", PO, u"Muro Secreto", PL, u"Sekretna Ściana", RU, u"Секретная Стена", JP, u"秘密の壁", KO, u"비밀의 벽", CN, u"秘密墙", TH, u"กำแพงลับ");}
CChar* TSelect() {return MLTC(u"Select", DE, u"Auswählen", FR, u"Sélectionner", IT, u"Selezionare", SP, u"Seleccione", PO, u"Selecionar", PL, u"Wybierz", RU, u"Выбирать", JP, u"選択する", KO, u"고르다", CN, u"选择", TH, u"เลือก");}
CChar* TSelectAll() {return MLTC(u"Select All", DE, u"Alle", FR, u"Tout", IT, u"Tutti", SP, u"Todos", PO, u"Todo", PL, u"Wszystko", RU, u"Все", JP, u"すべて選択", KO, u"모두 선택", CN, u"全选", TH, u"เลือกทั้งหมด");}
CChar* TSelectAmount() {return MLTC(u"Please select the amount", DE, u"Wählen Sie Betrag", FR, u"Sélectionnez le montant", IT, u"Seleziona Importo", SP, u"Seleccionar cantidad", PO, u"Selecione o valor", PL, u"Wybierz ilość", RU, u"Выберите сумму", JP, u"金額を選択", KO, u"금액 선택", CN, u"选择金额", TH, u"เลือกจำนวนเงิน");}
CChar* TSelectGraphicsStyle() {return MLTC(u"Select Graphics Style", DE, u"Wählen Sie Grafikstil", FR, u"Sélectionnez le Style Graphique", IT, u"Seleziona Stile Grafico", SP, u"Seleccionar Estilo de Gráficos", PO, u"Selecionar Estilo Gráfico", PL, u"Wybierz Styl Grafiki", RU, u"Выберите стиль графики", JP, u"グラフィックスタイルを選択", KO, u"그래픽 스타일 선택", CN, u"选择图形样式", TH, u"เลือกรูปแบบกราฟิก");}
CChar* TSelectHero() {return MLTC(u"Select Hero", DE, u"Held", FR, u"Héros", IT, u"Eroe", SP, u"Héroe", PO, u"Herói", PL, u"Bohater", RU, u"Герой", JP, u"ヒーロー", KO, u"영웅", CN, u"英雄", TH, u"ฮีโร่");}
CChar* TSelectName() {return MLTC(u"Please select the name", DE, u"Bitte wählen Sie den Namen aus", FR, u"Veuillez sélectionner le nom", IT, u"Si prega di selezionare il nome", SP, u"Por favor seleccione el nombre", PO, u"Por favor, selecione o nome", PL, u"Proszę wybrać nazwę", RU, u"Пожалуйста, выберите имя", JP, u"名前を選択してください", KO, u"이름을 선택하세요", CN, u"请选择名称", TH, u"กรุณาเลือกชื่อ");}
CChar* TSelectPet() {return MLTC(u"Select Pet", DE, u"Haustier", FR, u"Animal", IT, u"Animale", SP, u"Mascota", PO, u"Lacaio", PL, u"Zwierzątko", RU, u"Питомец", JP, u"ペット", KO, u"애완 동물", CN, u"宠物", TH, u"สัตว์เลี้ยง");}
CChar* TSelectYourHero() {return MLTC(u"Select Your Hero", DE, u"Wählen Sie Ihren Helden aus", FR, u"Sélectionnez votre héros", IT, u"Seleziona il tuo eroe", SP, u"Selecciona tu héroe", PO, u"Selecione seu herói", PL, u"Wybierz swojego bohatera", RU, u"Выберите своего героя", JP, u"ヒーローを選択", KO, u"영웅 선택", CN, u"选择你的英雄", TH, u"เลือกฮีโร่ของคุณ");}
CChar* TSell() {return MLTC(u"Sell", DE, u"Verkaufen", FR, u"Vendre", IT, u"Vendere", SP, u"Vender", PO, u"Vender", PL, u"Sprzedaj", RU, u"Продавать", JP, u"売る", KO, u"팔다", CN, u"卖", TH, u"ขาย");}
CChar* TSend() {return MLTC(u"Send", DE, u"Schicken", FR, u"Envoyer", IT, u"Spedire", SP, u"Enviar", PO, u"Mandar", PL, u"Wyślij", RU, u"Отправлять", JP, u"送信", KO, u"보내다", CN, u"发送", TH, u"ส่ง");}
CChar* TSending() {return MLTC(u"Sending", DE, u"Senden", FR, u"Envoi en cours", IT, u"Invio", SP, u"Enviando", PO, u"Enviando", PL, u"Wysyłane", RU, u"Отправка", JP, u"送信", KO, u"배상", CN, u"发送", TH, u"การส่ง");}
CChar* TSettings() {return MLTC(u"Settings", DE, u"Einstellungen", FR, u"Réglages", IT, u"Impostazioni", SP, u"Ajustes", PO, u"Definições", PL, u"Ustawienia", RU, u"Настройки", JP, u"設定", KO, u"설정", CN, u"设置", TH, u"การตั้งค่า");}
CChar* TShadows() {return MLTC(u"Shadows", DE, u"Schatten", FR, u"Ombres", IT, u"Ombre", SP, u"Oscuridad", PO, u"Sombras", PL, u"Cienie", RU, u"Тени", JP, u"影", KO, u"그림자", CN, u"阴影", TH, u"เงา");}
CChar* TShadowsResolution() {return MLTC(u"Shadowmap Size", DE, u"Schattenauflösung", FR, u"Résolution des Ombres", IT, u"Risoluzione Ombre", SP, u"Resolución de Sombras", PO, u"Resolução de Sombras", PL, u"Rozdzielczość Cieni", RU, u"Разрешение Теней", JP, u"シャドウの解決", KO, u"그림자 해상도", CN, u"阴影分辨率", TH, u"ความละเอียดของเงา");}
CChar* TShadowsSofting() {return MLTC(u"Shadows Softing", DE, u"Schatten Weichmachen", FR, u"Adoucissement des Ombres", IT, u"Ombre che si Attenuano", SP, u"Suavizado de Sombras", PO, u"Suavização de Sombras", PL, u"Zmiękczanie Cieni", RU, u"Смягчение Теней", JP, u"影が柔らかくなる", KO, u"섀도우 소프트닝", CN, u"阴影柔和", TH, u"เงาอ่อนลง");}
CChar* TShadowsDither() {return MLTC(u"Shadow Jittering", DE, u"Schattendithering", FR, u"Tramage d'Ombre", IT, u"Dithering dell'Ombra", SP, u"Tramado de Sombras", PO, u"Pontilhamento de Sombra", PL, u"Roztrząsanie Cieni", RU, u"Сглаживание Теней", JP, u"シャドウディザリング", KO, u"그림자 디더링", CN, u"阴影抖动", TH, u"การทำสีเงา");}
CChar* TSharpen() {return MLTC(u"Sharpen", DE, u"Schärfen", FR, u"Aiguiser", IT, u"Affilare", SP, u"Afilar", PO, u"Afiado", PL, u"Wyostrz", RU, u"Резкость", JP, u"研ぐ", KO, u"갈다", CN, u"锐化", TH, u"ลับคม");}
CChar* TShield() {return MLTC(u"Shield", DE, u"Schild", FR, u"Bouclier", IT, u"Scudo", SP, u"Blindaje", PO, u"Escudo", PL, u"Tarcza", RU, u"Щит", JP, u"シールド", KO, u"방패", CN, u"盾", TH, u"โล่");}
CChar* TShieldPotion() {return MLTC(u"Shield Potion", DE, u"Schildtrank", FR, u"Potion de Bouclier", IT, u"Pozione Scudo", SP, u"Poción de Escudo", PO, u"Poção de Escudo", PL, u"Eliksir Tarczy", RU, u"Зелье Защиты", JP, u"シールドポーション", KO, u"방패 물약", CN, u"护盾药水", TH, u"ยาโล่");}
CChar* TShop() {return MLTC(u"Shop", DE, u"Einkaufen", FR, u"Boutique", IT, u"Negozio", SP, u"Tienda", PO, u"Comprar", PL, u"Sklep", RU, u"Магазин", JP, u"店", KO, u"가게", CN, u"店铺", TH, u"ร้านค้า");}
CChar* TShowHints() {return MLTC(u"Show Hints", DE, u"Zeige Hinweise", FR, u"Montrer Indices", IT, u"Mostra Suggerimenti", SP, u"Muestra Pistas", PO, u"Mostrar as Dicas", PL, u"Pokaż Wskazówki", RU, u"Показать Подсказки", JP, u"ヒントを表示", KO, u"힌트 보기", CN, u"显示提示", TH, u"แสดงคำแนะนำ");}
CChar* TShowPlayerLevel() {return MLTC(u"Show Player Level", DE, u"Spielerlevel Anzeigen", FR, u"Afficher le Niveau du Joueur", IT, u"Mostra Livello Giocatore", SP, u"Mostrar Nivel de Jugador", PO, u"Mostrar Nível do Jogador", PL, u"Pokaż Poziom Gracza", RU, u"Показать Уровень Игрока", JP, u"プレーヤーレベルを表示", KO, u"플레이어 레벨 표시", CN, u"显示玩家等级", TH, u"แสดงระดับผู้เล่น");}
CChar* TSickle() {return MLTC(u"Sickle", DE, u"Sichel", FR, u"Faucille", IT, u"Falce", SP, u"Hoz", PO, u"Foice", PL, u"Sierp", RU, u"Серп", JP, u"鎌", KO, u"낫", CN, u"镰刀", TH, u"เคียว");}
CChar* TSize() {return MLTC(u"Size", DE, u"Größe", FR, u"Taille", IT, u"Dimensione", SP, u"Tamaño", PO, u"Tamanho", PL, u"Rozmiar", RU, u"Размер", JP, u"サイズ", KO, u"크기", CN, u"尺寸", TH, u"ขนาด");}
CChar* TSmall(TRANS_FORM form) {return MLTC(u"Small", DE, u"Klein", FR, u"Petit", IT, u"Piccolo", SP, u"Pequeño", PO, u"Pequeno", PL, (form==TF_MALE) ? u"Mały" : (form==TF_FEMALE) ? u"Mała" : u"Małe", RU, u"Небольшой", JP, u"小さい", KO, u"작은", CN, u"小的", TH, u"เล็ก");}
CChar* TSnakes() {return MLTC(u"Snakes", DE, u"Schlangen", FR, u"Serpents", IT, u"Serpenti", SP, u"Serpientes", PO, u"Cobras", PL, u"Węże", RU, u"Змеи", JP, u"ヘビ", KO, u"뱀", CN, u"蛇", TH, u"งู");}
CChar* TSoftParticles() {return MLTC(u"Soft Particles", DE, u"Weiche Partikel", FR, u"Particules Molles", IT, u"Particelle Morbide", SP, u"Partículas Blandas", PO, u"Partículas Moles", PL, u"Miękkie Partikle", RU, u"Мягкие Частицы", JP, u"柔らかい粒子", KO, u"부드러운 입자", CN, u"软粒子", TH, u"อนุภาคอ่อน");}
CChar* TSoundVolume() {return MLTC(u"Sound Volume", DE, u"Lautstärke", FR, u"Volume Sonore", IT, u"Volume del Suono", SP, u"Volumen de Sonido", PO, u"Volume do Som", PL, u"Głośność Dźwięku", RU, u"Громкость", JP, u"音量", KO, u"사운드 볼륨", CN, u"音量", TH, u"ระดับเสียง");}
CChar* TSpear() {return MLTC(u"Spear", DE, u"Speer", FR, u"Lance", IT, u"Lancia", SP, u"Lanza", PO, u"Lança", PL, u"Włócznia", RU, u"Копье", JP, u"槍", KO, u"창", CN, u"矛", TH, u"หอก");}
CChar* TSpecialThanksTo() {return MLTC(u"Special Thanks to", DE, u"Besonderer Dank an", FR, u"Remerciement spécial à", IT, u"Ringraziamenti speciali a", SP, u"Agradecimientos especiales a", PO, u"Agradecimentos especiais para", PL, u"Specjalne podziękowania dla", RU, u"Отдельное спасибо", JP, u"特別に感謝します", KO, u"특별히 감사함", CN, u"特别感谢", TH, u"ขอขอบคุณเป็นพิเศษ");}
CChar* TSpeed() {return MLTC(u"Speed", DE, u"Geschwind."/*Geschwindigkeit*/, FR, u"Vitesse", IT, u"Velocità", SP, u"Velocidad", PO, u"Velocidade", PL, u"Szybkość", RU, u"Скорость", JP, u"スピード", KO, u"속도", CN, u"速度", TH, u"ความเร็ว");}
CChar* TSpellBook() {return MLTC(u"Spell Book", DE, u"Zauberbuch", FR, u"Livre de sortilèges", IT, u"Libro degli incantesimi", SP, u"Libro de hechizos", PO, u"Livro de feitiços", PL, u"Księga Czarów", RU, u"Книга Заклинаний", JP, u"魔法書", KO, u"마법서", CN, u"拼写书", TH, u"หนังสือเวทย์มนตร์");}
CChar* TSpiders() {return MLTC(u"Spiders", DE, u"Spinnen", FR, u"Araignées", IT, u"Ragni", SP, u"Arañas", PO, u"Aranhas", PL, u"Pająki", RU, u"Пауки", JP, u"蜘蛛", KO, u"거미", CN, u"蜘蛛", TH, u"แมงมุม");}
CChar* TStaff() {return MLTC(u"Staff", DE, u"Stab", FR, u"Staff", IT, u"Staff", SP, u"Bastón", PO, u"Bastão", PL, u"Laska", RU, u"Посох", JP, u"杖", KO, u"지팡이", CN, u"棍", TH, u"ไม้เท้า");}
CChar* TStairsDown() {return MLTC(u"Stairs Down", DE, u"Treppe Runter", FR, u"Escaliers vers le bas", IT, u"Scale Giù", SP, u"Escaleras Abajo", PO, u"Escadas para baixo", PL, u"Schody w Dół", RU, u"Лестница Вниз", JP, u"階段を下りる", KO, u"아래로 계단", CN, u"下楼梯", TH, u"ลงบันได");}
CChar* TStairsUp() {return MLTC(u"Stairs Up", DE, u"Treppe Hoch", FR, u"Escaliers en haut", IT, u"Scale in Alto", SP, u"Escaleras Arriba", PO, u"Escadas para Cima", PL, u"Schody w Górę", RU, u"Лестница Вверх", JP, u"階段を上る", KO, u"위로 계단", CN, u"上楼梯", TH, u"บันไดขึ้น");}
CChar* TStorage() {return MLTC(u"Storage", DE, u"Lager", FR, u"Espace de rangement", IT, u"Conservazione", SP, u"Almacenamiento", PO, u"Armazenar", PL, u"Przechowalnia", RU, u"Место хранения", JP, u"保管所", KO, u"저장", CN, u"贮存", TH, u"พื้นที่จัดเก็บ");}
CChar* TStrength() {return MLTC(u"Strength", DE, u"Stärke", FR, u"Force", IT, u"Forza", SP, u"Fuerza", PO, u"Força", PL, u"Siła", RU, u"Прочность", JP, u"強さ", KO, u"힘", CN, u"力量", TH, u"ความแข็งแกร่ง");}
CChar* TSword() {return MLTC(u"Sword", DE, u"Schwert", FR, u"Épée", IT, u"Spada", SP, u"Espada", PO, u"Espada", PL, u"Miecz", RU, u"Меч", JP, u"剣", KO, u"검", CN, u"剑", TH, u"ดาบ");}
CChar* TSynchronization() {return MLTC(u"Synchronization", DE, u"Synchronisation", FR, u"Synchronisation", IT, u"Sincronizzazione", SP, u"Sincronización", PO, u"Sincronização", PL, u"Synchronizacja", RU, u"Синхронизация", JP, u"同期", KO, u"동기화", CN, u"同步", TH, u"การซิงโครไนซ์");}
CChar* TTakeAll() {return MLTC(u"Take All", DE, u"Nimm alles", FR, u"Prendre toutes", IT, u"Prendi tutto", SP, u"Tomalo todo", PO, u"Leve tudo", PL, u"Weź wszystko", RU, u"Взять все", JP, u"すべて取ります", KO, u"전부 다 가져", CN, u"拿走所有", TH, u"เอาทั้งหมด");}
CChar* TTakeAllItems() {return MLTC(u"Take All Items", DE, u"Nimm alle Gegenstände", FR, u"Prendre tous les articles", IT, u"Prendi tutti gli articoli", SP, u"Tomar todos los artículos", PO, u"Pegue todos os itens", PL, u"Weź wszystkie przedmioty", RU, u"Взять все предметы", JP, u"すべてのアイテムを取る", KO, u"모든 항목 가져오기", CN, u"拿走所有物品", TH, u"รับทุกรายการ");}
CChar* TTeleport() {return MLTC(u"Teleport", DE, u"Teleportieren", FR, u"Téléportation", IT, u"Teletrasporto", SP, u"Teletransportarse", PO, u"Teleporte", PL, u"Teleport", RU, u"Телепорт", JP, u"テレポート", KO, u"텔레포트", CN, u"传送", TH, u"เทเลพอร์ต");}
CChar* TTextureFiltering() {return MLTC(u"Texture Filtering", DE, u"Texturfilterung", FR, u"Filtrage de Texture", IT, u"Filtraggio delle Texture", SP, u"Filtrado de Texturas", PO, u"Filtragem de Textura", PL, u"Filtrowanie Tekstur", RU, u"Фильтрация Текстур", JP, u"テクスチャフィルタリング", KO, u"텍스처 필터링", CN, u"纹理过滤", TH, u"เนื้อผ้ากรอง");}
CChar* TTextureSize() {return MLTC(u"Texture Size", DE, u"Texturgröße", FR, u"Taille des Textures", IT, u"Dimensione della Trama", SP, u"Tamaño de Textura", PO, u"Tamanho da Textura", PL, u"Rozmiar Tekstur", RU, u"Размер Текстуры", JP, u"テクスチャサイズ", KO, u"텍스처 크기", CN, u"纹理大小", TH, u"ขนาดพื้นผิว");}
CChar* TThanksForPlaying() {return MLTC(u"Thanks for playing", DE, u"Danke fürs Spielen", FR, u"Merci d'avoir joué", IT, u"Grazie per aver giocato", SP, u"Gracias por jugar", PO, u"Obrigado por jogar", PL, u"Dzięki za granie", RU, u"Спасибо за игру", JP, u"遊んでくれてありがとう", KO, u"플레이해주셔서 감사합니다", CN, u"感谢参与", TH, u"ขอบคุณสำหรับการเล่น");}
CChar* TThrown() {return MLTC(u"Thrown", DE, u"Wurfwaffe", FR, u"Arme de jet", IT, u"Arma lanciata", SP, u"Arma Arrojadiza", PO, u"Arma de Arremesso", PL, u"Rzucona Broń", RU, u"Метательное Оружие", JP, u"投擲武器", KO, u"투척 무기", CN, u"投掷武器", TH, u"อาวุธขว้าง");} // Thrown Weapon
CChar* TToggleFullscreen() {return MLTC(u"Toggle Fullscreen", DE, u"Vollbild umschalten", FR, u"Basculer en plein écran", IT, u"Passare a schermo intero", SP, u"Alternar pantalla completa", PO, u"Alternar para o modo tela cheia", PL, u"Zmień pełny ekran", RU, u"Включить полноэкранный режим", JP, u"フルスクリーン切り替え", KO, u"전체 화면 전환", CN, u"切换全屏", TH, u"สลับโหมดเต็มหน้าจอ");}
CChar* TToggleWeaponSet() {return MLTC(u"Toggle Weapon Set", DE, u"Waffe umschalten", FR, u"Basculer l'arme", IT, u"Attiva/disattiva arma", SP, u"Alternar arma", PO, u"Alternar arma", PL, u"Zmień broń", RU, u"Переключить оружие", JP, u"トグルウェポン", KO, u"무기 토글", CN, u"切换武器", TH, u"สลับอาวุธ");}
CChar* TToneMapping() {return MLTC(u"Tone Mapping", DE, u"Tone Mapping", FR, u"Mappage Ton Local", IT, u"Mappatura dei Toni", SP, u"Mapeo Tonal", PO, u"Mapeamento de Tons", PL, u"Mapowanie Tonów", RU, u"Тональное Отображение", JP, u"トーンマッピング", KO, u"톤 매핑", CN, u"色调映射", TH, u"การทำแผนที่เสียง");}
CChar* TTreasure() {return MLTC(u"Treasure", DE, u"Schatz", FR, u"Trésor", IT, u"Tesoro", SP, u"Tesoro", PO, u"Tesouro", PL, u"Skarb", RU, u"Сокровище", JP, u"宝物", KO, u"보물", CN, u"宝藏", TH, u"สมบัติ");}
CChar* TTurnLeft() {return MLTC(u"Turn Left", DE, u"Biegen Sie links ab", FR, u"Tourner à gauche", IT, u"Girare a sinistra", SP, u"Gire a la izquierda", PO, u"Vire à esquerda", PL, u"Obróć w lewo", RU, u"Поверните Налево", JP, u"左折してください", KO, u"왼쪽으로 돌아", CN, u"左转", TH, u"เลี้ยวซ้าย");}
CChar* TTurnRight() {return MLTC(u"Turn Right", DE, u"Biegen Sie rechts ab", FR, u"Tournez à droite", IT, u"Girare a destra", SP, u"Gire a la derecha", PO, u"Vire à direita", PL, u"Obróć w prawo", RU, u"Поверните направо", JP, u"右折", KO, u"우회전", CN, u"右转", TH, u"เลี้ยวขวา");}
CChar* TType() {return MLTC(u"Type", DE, u"Art", FR, u"Taper", IT, u"Tipo", SP, u"Escribe", PO, u"Tipo", PL, u"Rodzaj", RU, u"Тип", JP, u"タイプ", KO, u"유형", CN, u"类型", TH, u"พิมพ์");}
CChar* TUnequip() {return MLTC(u"Unequip", DE, u"Ausrüsten", FR, u"Déséquiper", IT, u"Disequipaggiare", SP, u"Desequipar", PO, u"Desequipar", PL, u"Zdejmij"/*Odłóż*/, RU, u"Снять", JP, u"装備を解除する", KO, u"장비 해제", CN, u"取消装备", TH, u"ถอด");}
CChar* TUnlocked() {return MLTC(u"Unlocked", DE, u"Entsperrt", FR, u"Débloqué", IT, u"Sbloccato", SP, u"Desbloqueado", PO, u"Desbloqueado", PL, u"Otworzono", RU, u"Разблокирован", JP, u"ロックを解除", KO, u"잠금 해제", CN, u"解锁", TH, u"ปลดล็อค");}
CChar* TUpdated() {return MLTC(u"Updated", DE, u"Aktualisiert", FR, u"Mis à Jour", IT, u"Aggiornato", SP, u"Actualizado", PO, u"Atualizado", PL, u"Zaktualizowano", RU, u"Обновлено", JP, u"更新しました", KO, u"업데이트됨", CN, u"更新", TH, u"อัปเดต");}
CChar* TUpload() {return MLTC(u"Upload", DE, u"Hochladen", FR, u"Télécharger", IT, u"Caricamento", SP, u"Subir", PO, u"Carregar", PL, u"Wgraj", RU, u"Загрузить", JP, u"アップロード", KO, u"업로드", CN, u"上传", TH, u"ที่อัพโหลด");}
CChar* TUpscaleFiltering() {return MLTC(u"Upscale Filtering", DE, u"Skalierung", FR, u"Filtration", IT, u"Filtraggio", SP, u"Interpolación", PO, u"Filtrando", PL, u"Filtrowanie", RU, u"Фильтрация", JP, u"画像スケーリング", KO, u"이미지 스케일링", CN, u"图像缩放", TH, u"การกรองระดับหรู");}
CChar* TUseItem() {return MLTC(u"Use Item", DE, u"Gegenstand Verwenden", FR, u"Utiliser un Objet", IT, u"Usa Oggetto", SP, u"Usar Objeto", PO, u"Usar Item", PL, u"Użyj Przedmiot", RU, u"Использовать Предмет", JP, u"使用アイテム", KO, u"아이템 사용", CN, u"使用物品", TH, u"ใช้ไอเทม");}
CChar* TVersion() {return MLTC(u"Version", DE, u"Ausführung", FR, u"Version", IT, u"Versione", SP, u"Versión", PO, u"Versão", PL, u"Wersja", RU, u"Версия", JP, u"バージョン", KO, u"버전", CN, u"版本", TH, u"เวอร์ชั่น");}
CChar* TVeryHigh(TRANS_FORM form) {return MLTC(u"Very High", DE, u"Sehr Hoch", FR, u"Très haut", IT, u"Molto Alto", SP, u"Muy Alto", PO, u"Muito Alto", PL, (form==TF_MALE) ? u"Bardzo Wysoki" : (form==TF_FEMALE) ? u"Bardzo Wysoka" : u"Bardzo Wysokie", RU, u"Очень Высоко", JP, u"非常に高い", KO, u"매우 높음", CN, u"很高", TH, u"สูงมาก");}
CChar* TVitality() {return MLTC(u"Vitality", DE, u"Vitalität", FR, u"Vitalité", IT, u"Vitalità", SP, u"Vitalidad", PO, u"Vitalidade", PL, u"Żywotność", RU, u"Жизненность", JP, u"活力", KO, u"활력", CN, u"活力", TH, u"ความมีชีวิตชีวา");}
CChar* TWand() {return MLTC(u"Wand", DE, u"Zauberstab", FR, u"Baguette Magique", IT, u"Bacchetta", SP, u"Varita", PO, u"Varinha", PL, u"Różdżka", RU, u"Палочка", JP, u"ワンド", KO, u"지팡이", CN, u"棍棒", TH, u"ไม้กายสิทธิ์");}
CChar* TWalk() {return MLTC(u"Walk", DE, u"Gehen", FR, u"Marcher", IT, u"Camminare", SP, u"Andar", PO, u"Caminhar", PL, u"Chód", RU, u"Ходить", JP, u"歩く", KO, u"걷다", CN, u"走", TH, u"เดิน");}
CChar* TWallLever() {return MLTC(u"Wall Lever", DE, u"Wandhebel", FR, u"Levier Mural", IT, u"Leva a Muro", SP, u"Palanca de Pared", PO, u"Alavanca de Parede", PL, u"Ścienna Dźwignia", RU, u"Настенный Рычаг", JP, u"ウォールレバー", KO, u"벽 레버", CN, u"墙杆", TH, u"ก้านโยกติดผนัง");}
CChar* TWallText() {return MLTC(u"Wall Text", DE, u"Wandtext", FR, u"Texte Mural", IT, u"Testo da Parete", SP, u"Texto de Pared", PO, u"Texto da Parede", PL, u"Tekst na Ścianie", RU, u"Текст на Стене", JP, u"壁のテキスト", KO, u"벽 텍스트", CN, u"墙壁文字", TH, u"ข้อความติดผนัง");}
CChar* TWallTurret() {return MLTC(u"Wall Turret", DE, u"Wandrevolver", FR, u"Tourelle Murale", IT, u"Torretta Muraria", SP, u"Torreta de Pared", PO, u"Torre de Muralha", PL, u"Ścienna Wieża", RU, u"Настенная Турель", JP, u"ウォールタレット", KO, u"벽 포탑", CN, u"墙炮塔", TH, u"กำแพงป้อมปืน");}
CChar* TWouldYouLikeToChangeName() {return MLTC(u"Would you like to change the name?", DE, u"Möchten Sie den Namen ändern?", FR, u"Souhaitez-vous changer le nom?", IT, u"Vuoi cambiare il nome?", SP, u"Te gustaría cambiar el nombre?", PO, u"Gostaria de mudar o nome?", PL, u"Czy chcesz zmienić nazwę?", RU, u"Хотели бы вы изменить имя?", JP, u"名前を変更しますか？", KO, u"이름을 변경하시겠습니까?", CN, u"您想更改名称吗？", TH, u"คุณต้องการที่จะเปลี่ยนชื่อ?");}
CChar* TYes() {return MLTC(u"Yes", DE, u"Jawohl", FR, u"Oui", IT, u"Sì", SP, u"Sí", PO, u"Sim", PL, u"Tak", RU, u"Да", JP, u"はい", KO, u"네", CN, u"是的", TH, u"ใช่");}
CChar* TYouHaveDied() {return MLTC(u"You have died.", DE, u"Du bist gestorben.", FR, u"Vous êtes morts.", IT, u"Sei morto.", SP, u"Te has muerto.", PO, u"Você morreu.", PL, u"Umarłeś.", RU, u"Вы умерли.", JP, u"あなたは死にました。", KO, u"당신은 죽었습니다.", CN, u"你已经死了。", TH, u"คุณเสียชีวิตแล้ว");}
CChar* TYourEmail() {return MLTC(u"Your Email", DE, u"Deine Email", FR, u"Votre Email", IT, u"La Tua Email", SP, u"Email", PO, u"Seu Email", PL, u"Twój Email", RU, u"Email", JP, u"あなたのメール", KO, u"귀하의 이메일", CN, u"你的邮件", TH, u"อีเมลของคุณ");}
CChar* TZombies() {return MLTC(u"Zombies", DE, u"Zombies", FR, u"Morts Vivants", IT, u"Zombi", SP, u"Zombis", PO, u"Zumbis", PL, u"Zombie", RU, u"Зомби", JP, u"ゾンビ", KO, u"좀비", CN, u"僵尸", TH, u"ซอมบี้");}
CChar* TZoom() {return MLTC(u"Zoom", DE, u"Zoomen", FR, u"Zoom", IT, u"Ingrandisci", SP, u"Zoom", PO, u"Ampliação", PL, u"Powiększ", RU, u"Увеличить", JP, u"ズーム", KO, u"줌", CN, u"飞涨", TH, u"ซูม");}
/******************************************************************************/
}
/******************************************************************************/
